### PR TITLE
azure-podvm-image-build: Use repository vars

### PR DESCRIPTION
**Pull request by surajssd**
Use repository vars instead of hardcoded values. This makes it easier to test in an alternate CI setup created on private Azure accounts.

### CODE REVIEW

**Review by bpradipt — APPROVED** [review]
/lgtm

**Review by mkulke — COMMENTED** [review]
If we make this a secret it will be masked from the output `***`, so it cannot be copy/pasted around. it's a minor nuisance, but I'm not sure I like the practice of putting non-secrets in the secret store.

If we want environment specific settings, we can use variables in the `environment` facility, no?

image

**Comment by katexochen** [comment]
> This makes it easier to test in an alternate CI setup created on private Azure accounts.

What exactly are we trying to protect here? Do you just want to inject the values, or do they require protection? And where do you want to execute the workflow with these values, on the main repo or on a fork?

**Comment by surajssd** [comment]
> What exactly are we trying to protect here? Do you just want to inject the values, or do they require protection? And where do you want to execute the workflow with these values, on the main repo or on a fork?

I think more than protection it is about having a programmable way to recreate an alternate CI set up to test stuff. And having stuff hardcoded makes it error prone. 

@mkulke Yes we can use the variables and not secrets.

**Review by katexochen — APPROVED** [review]

**Review by mkulke — APPROVED** [review]

**Pull request merged**
