### PR TITLE
podnetwork: Handle network interface with multiple addresses

### PR DESCRIPTION
**Pull request by bpradipt**
Fixes: #357

Signed-off-by: Pradipta Banerjee <pradipta.banerjee@gmail.com>

### CODE REVIEW

**Review by snir911 — APPROVED** [review]
Is it possible addrs[0] will contain wrong IP? anyhow, i guess for now it's good enough, thanks!

**Review by knrt10 — APPROVED** [review]

**Comment by bpradipt** [comment]
> Is it possible addrs[0] will contain wrong IP? anyhow, i guess for now it's good enough, thanks!

Possible. We need an improved mechanism to get the worker node IP.

**Comment by huoqifeng** [comment]
> > Is it possible addrs[0] will contain wrong IP? anyhow, i guess for now it's good enough, thanks!
> 
> Possible. We need an improved mechanism to get the worker node IP.

I'm also worry about it, maybe @yoheiueda can comment on that?

**Comment by bpradipt** [comment]
> > > Is it possible addrs[0] will contain wrong IP? anyhow, i guess for now it's good enough, thanks!
> > 
> > 
> > Possible. We need an improved mechanism to get the worker node IP.
> 
> I'm also worry about it, maybe @yoheiueda can comment on that?

Just to be clear, the existing code already used the first IP address of the network device. Just that it returned error when there were more than one ip addresses in the network device, which effectively meant that the code can only handle network interface with single IP address. So this PR just corrects that.

We do need a better (and faster) mechanism to get the worker node IP. Since we run cloud-api-adaptor as a pod, we might be able to use `downward api` to get the worker node primary IP and use the same. I can do that in a separate PR.

**Review by yoheiueda — APPROVED** [review]
LGTM.

I think my original implementation is too conservative to handle various network configurations. The intention of the code was to notify users if there is ambiguity when cloud-api-adaptor decides worker node IP address. I think showing a warning message is enough for now.

**Pull request merged**
