### PR TITLE
Default agent config

### PR DESCRIPTION
**Pull request by stevenhorsman**
Add agent image section to stop signature verification being enabled

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @stevenhorsman!

**Comment by stevenhorsman** [comment]
Just testing this manually for ibmcloud, @bpradipt @knrt10 (as representatives of the other cloud providers) - if you are able to work with your teams and see if it works, either before or after we merge it based on time allowed, that would be great. Thanks!

**Comment by fidencio** [comment]
@stevenhorsman, @caavery, for the vsphere side the code related to the VM creation is not yet merged, but it'll have to be updated accordingly to what you did here.

This is the part of the PR that will have to be changed: https://github.com/confidential-containers/cloud-api-adaptor/pull/336/files#diff-ace739aba5f368e777a1fa09ac8bce05478a32ab8a2dd828ca2841f97a48e076R6

**Comment by stevenhorsman** [comment]
It didn't work for ibmcloud - I naively assumed that any files within image/files would be added to the peer-pod vm images, but I think I was wrong. @yoheiueda - can you correct me please. Thanks!

**Comment by stevenhorsman** [comment]
Even updating my the ansible to point to my branch I'm still hitting failures and the peer pod seems to fail with communication between the agent protocol forwarder and agent:
```
# kubectl describe pods
Name:                nginx
Namespace:           default
Priority:            0
Runtime Class Name:  kata
Service Account:     default
Node:                peer-pod-cluster-worker/10.244.64.5
Start Time:          Fri, 04 Nov 2022 19:25:15 +0000
Labels:              app=nginx
...
Events:
  Type     Reason                  Age                From               Message
  ----     ------                  ----               ----               -------
  Normal   Scheduled               7m55s              default-scheduler  Successfully assigned default/nginx to peer-pod-cluster-worker
  Warning  FailedCreatePodSandBox  117s (x2 over 5m)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: agent connection is not established: reaches max retry count. gave up establishing agent connection to /run/kata-containers/agent.sock: dial unix /run/kata-containers/agent.sock: connect: no such file or directory: unknown
```

**Comment by stevenhorsman** [comment]
After long while debugging I think the issue is that having an agent-config.toml specified means that the `Environment="KATA_AGENT_SERVER_ADDR=unix:///run/kata-containers/agent.sock"` section is getting ignored:
```
Started Kata Agent.
Nov 04 19:56:24 podvm-nginx-1e638d73 kata-agent[698]: {"msg":"announce","level":"INFO","ts":"2022-11-04T19:56:24.585918146Z","source":"agent","pid":"698","subsystem":"root","version":"0.1.0","name":"kata-agent","api-version":"0.0.1","agent-version":"3.1.0-alpha0","config":"AgentConfig { debug_console: false, dev_mode: false, log_level: Info, hotplug_timeout: 3s, debug_console_vport: 0, log_vport: 0, container_pipe_size: 0, server_addr: \"vsock://-1:1024\", unified_cgroup_hierarchy: false, tracing: false, endpoints: AgentEndpoints { allowed: {}, all_allowed: false }, supports_seccomp: true, container_policy_path: \"\", aa_kbc_params: \"\", https_proxy: \"\", no_proxy: \"\", data_integrity: false, enable_signature_verification: false }","agent-commit":"3.1.0-alpha0-656a3e06a7e406fa8105619c16d3568365fbac44"}
```
I'm not sure why, but I'll try pushing a fix that moves that into the agent-config and see if that helps.

**Comment by stevenhorsman** [comment]
I was hitting some failures with this PR and realised it is due to an upstream change that went into the agent config logic has what I think is a bug: If you have an agent config, but don’t specify endpoints then we don’t set all_allowed to true, so you end up with something like:
kata-agent[696]: {"msg":"announce","level":"INFO","ts":"2022-11-06T16:51:44.871119029Z","source":"agent","subsystem":"root","version":"0.1.0","pid":"696","name":"kata-agent","api-version":"0.0.1","config":"AgentConfig { debug_console: false, dev_mode: false, log_level: Info, hotplug_timeout: 3s, debug_console_vport: 0, log_vport: 0, container_pipe_size: 0, server_addr: \"unix:///run/kata-containers/agent.sock\", unified_cgroup_hierarchy: false, tracing: false, endpoints: AgentEndpoints { allowed: {}, all_allowed: false }, supports_seccomp: true, container_policy_path: \"\", aa_kbc_params: \"\", https_proxy: \"\", no_proxy: \"\", data_integrity: false, enable_signature_verification: false }","agent-commit":"3.1.0-alpha0-656a3e06a7e406fa8105619c16d3568365fbac44","agent-version":"3.1.0-alpha0"}
I’ve raised https://github.com/kata-containers/kata-containers/issues/5590, which I will try and fix tomorrow, but in the short term I've added https://github.com/confidential-containers/cloud-api-adaptor/pull/339/commits/9c658c26943b3113b3c1c18febce1cf75c949bff as a workaround.
With this PR the ibmcloud tests pass locally:
```
module.run_nginx_demo.null_resource.ansible (local-exec): PLAY [all] *********************************************************************

module.run_nginx_demo.null_resource.ansible (local-exec): TASK [Gathering Facts] *********************************************************
module.run_nginx_demo.null_resource.ansible: Still creating... [10s elapsed]
module.run_nginx_demo.null_resource.ansible (local-exec): ok: [10.244.64.4]

module.run_nginx_demo.null_resource.ansible (local-exec): TASK [Get Kubernetes worker architecture] **************************************
module.run_nginx_demo.null_resource.ansible: Still creating... [20s elapsed]
module.run_nginx_demo.null_resource.ansible (local-exec): changed: [10.244.64.4]

module.run_nginx_demo.null_resource.ansible (local-exec): TASK [Create Kubernetes resources for the nginx in peer pod demo] **************
module.run_nginx_demo.null_resource.ansible (local-exec): changed: [10.244.64.4]

module.run_nginx_demo.null_resource.ansible (local-exec): TASK [Wait for pod to be ready] ************************************************
module.run_nginx_demo.null_resource.ansible: Still creating... [30s elapsed]
module.run_nginx_demo.null_resource.ansible: Still creating... [40s elapsed]
module.run_nginx_demo.null_resource.ansible: Still creating... [50s elapsed]
module.run_nginx_demo.null_resource.ansible: Still creating... [1m0s elapsed]
module.run_nginx_demo.null_resource.ansible (local-exec): changed: [10.244.64.4]

module.run_nginx_demo.null_resource.ansible (local-exec): TASK [Check nginx container has started in the peer pod] ***********************
module.run_nginx_demo.null_resource.ansible: Still creating... [1m10s elapsed]
module.run_nginx_demo.null_resource.ansible (local-exec): changed: [10.244.64.4]

module.run_nginx_demo.null_resource.ansible (local-exec): TASK [Send HTTP request to nginx container] ************************************
module.run_nginx_demo.null_resource.ansible: Still creating... [1m20s elapsed]
module.run_nginx_demo.null_resource.ansible (local-exec): changed: [10.244.64.4]

module.run_nginx_demo.null_resource.ansible (local-exec): TASK [Delete the HTML document retrieved from nginx] ***************************
module.run_nginx_demo.null_resource.ansible (local-exec): changed: [10.244.64.4]

module.run_nginx_demo.null_resource.ansible (local-exec): TASK [Check peer pod VM architecture against the Kubernetes worker architecture] ***
module.run_nginx_demo.null_resource.ansible: Still creating... [1m30s elapsed]
module.run_nginx_demo.null_resource.ansible (local-exec): changed: [10.244.64.4]

module.run_nginx_demo.null_resource.ansible (local-exec): TASK [Check mounted volume from configMap] *************************************
module.run_nginx_demo.null_resource.ansible: Still creating... [1m40s elapsed]
module.run_nginx_demo.null_resource.ansible (local-exec): changed: [10.244.64.4]

module.run_nginx_demo.null_resource.ansible (local-exec): TASK [Check mounted volume from secret - username] *****************************
module.run_nginx_demo.null_resource.ansible: Still creating... [1m50s elapsed]
module.run_nginx_demo.null_resource.ansible (local-exec): changed: [10.244.64.4]

module.run_nginx_demo.null_resource.ansible (local-exec): TASK [Check mounted volume from secret - password] *****************************
module.run_nginx_demo.null_resource.ansible: Still creating... [2m0s elapsed]
module.run_nginx_demo.null_resource.ansible (local-exec): changed: [10.244.64.4]

module.run_nginx_demo.null_resource.ansible (local-exec): PLAY RECAP *********************************************************************
module.run_nginx_demo.null_resource.ansible (local-exec): 10.244.64.4                : ok=11   changed=10   unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

We now have a couple of choices - assuming the other commits are correct:
- Wait for https://github.com/kata-containers/kata-containers/issues/5590 to be fixed and then remove 9c658c26943b3113b3c1c18febce1cf75c949bff and re-test
- Merge this change with 9c658c26943b3113b3c1c18febce1cf75c949bff included to get us working right away, which doesn't harm anything, but is extra code. Then after https://github.com/kata-containers/kata-containers/issues/5590 is merged I can revert 9c658c26943b3113b3c1c18febce1cf75c949bff and re-test.
I'm happy to take views on this. \cc @yoheiueda @bpradipt

**Comment by yoheiueda** [comment]
@stevenhorsman thank you very much for taking care of this.

We can go ahead with https://github.com/confidential-containers/cloud-api-adaptor/commit/9c658c26943b3113b3c1c18febce1cf75c949bff

**Review by yoheiueda — APPROVED** [review]
LGTM

**Review by bpradipt — APPROVED** [review]
/lgtm
@stevenhorsman adding the endpoints in the agent config is fine.
Thanks..

**Pull request merged**
