### PR TITLE
test: use fatal for program exit errors in e2e test

### PR DESCRIPTION
**Pull request by huoqifeng**
Fixes: #726

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks Qifeng & Yohei for the suggestion

**Review by wainersm — APPROVED** [review]
With the @yoheiueda 's observation to remove the `os.exit(1)` calls.

Hey @huoqifeng  thanks! I saw you guys using the logger on the code for ibmcloud, I thought it would be a good improvement to the framework too but I forgot to say :(

**Comment by huoqifeng** [comment]
> `log.Fatal` internally calls `os.Exit(1)`, so I don't think you need to call `os.Exit(1)` by yourself here.
> 
> https://github.com/sirupsen/logrus/blob/v1.9.0/logger.go#L189-L191

Right, it will call os.Exit eventually https://github.com/sirupsen/logrus/blob/f8bf7650dccb756cea26edaf9217aab85500fe07/logger.go#L342, thanks @yoheiueda

**Review by yoheiueda — APPROVED** [review]
LGTM

**Pull request merged**
