### PR TITLE
ibmcloud: Added fixes to resolve unstable test results

### PR DESCRIPTION
**Pull request by sudharshanibm3**
Added fixes to resolve unstable test results in daily-e2e-test jenkins job

Fixes: #1127

### CODE REVIEW

**Comment by stevenhorsman** [comment]
Adding `hold` as we are in code freeze for 0.7.0 release

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks - lets get it merged once the code freeze has lifted

**Review by mattarnoatibm — APPROVED** [review]
LGTM

**Comment by jtumber-ibm** [comment]
removed hold as release has been completed

**Pull request merged**
