### PR TITLE
ibmcloud: Test Cases for checking peerpod with invalid authenticated images

### PR DESCRIPTION
**Pull request by sudharshanibm3**
Test Cases for checking PodVM with image from authenticated registry with invalid credentials

Fixes: #1159 

Note: Current PR is dependent on PR  #1157

### CODE REVIEW

**Comment by jtumber-ibm** [comment]
Can you combine these into one PR?

**Comment by sudharshanibm3** [comment]
Hi @jtumber-ibm ,
- As Current PR is dependent on the code of another PR- [#1157 ](https://github.com/confidential-containers/cloud-api-adaptor/pull/1157)
- Some of the functions from previous PR has been reused here
- So waiting for PR- [#1157](https://github.com/confidential-containers/cloud-api-adaptor/pull/1157) to be merged first, then planned rebase the current PR with merged one
Please let me know if any changes required in current plan?

**Comment by jtumber-ibm** [comment]
> Hi @jtumber-ibm ,
> 
>     * As Current PR is dependent on the code of another PR- [#1157 ](https://github.com/confidential-containers/cloud-api-adaptor/pull/1157)
> 
>     * Some of the functions from previous PR has been reused here
> 
>     * So waiting for PR- [#1157](https://github.com/confidential-containers/cloud-api-adaptor/pull/1157) to be merged first, then planned rebase the current PR with merged one
>       Please let me know if any changes required in current plan?

Can you not combine these changes into #1157 ? Not sure why they have been separated out

**Comment by sudharshanibm3** [comment]
Hi @jtumber-ibm ,
- Both commits has been added in PR [#1157](https://github.com/confidential-containers/cloud-api-adaptor/pull/1157)
- Can we close this PR as a duplicate?

**Pull request closed without merging**
