### PR TITLE
e2e-test: update kbs test case to support kbs with ibmse verifier

### PR DESCRIPTION
**Pull request by liudalibj**
- deploy kbs with ibmse verifer base on ENV IBM_SE_CREDS_DIR
- update kbs test case for libvrit provider to support kbs with ibmse verifier
- set key source before test cases
- `deny_all.rego` and `allow_with_wrong_image_tag.rego` are FAIL cases
- `allow_with_correct_claims.rego` is PASS case
- quay.io/curl/curl:latest do NOT have s390x support, replace the fail case to use busybox wget command

fixes https://github.com/confidential-containers/cloud-api-adaptor/issues/1934

### CODE REVIEW

**Comment by stevenhorsman** [comment]
@liudalibj - are you okay for this PR to go in post 0.9.0 release?

**Comment by liudalibj** [comment]
> @liudalibj - are you okay for this PR to go in post 0.9.0 release?

I am okay for this in in post 0.9.0 release.

**Comment by liudalibj** [comment]
One whole test log can be found at here https://github.com/liudalibj/cloud-api-adaptor/actions/runs/10104917246/job/27944630835 the `e2e-tests ibmse` section -> `check e2e-test result`
```
...
[2024-07-26T01:19:21.366Z] time="2024-07-26T03:19:20+02:00" level=info msg="default serviceAccount exists, namespace 'coco-pp-e2e-test-958a7109' is ready for use"
[2024-07-26T01:19:21.366Z] === RUN   TestLibvirtKbsKeyRelease
[2024-07-26T01:19:21.366Z] time="2024-07-26T03:19:20+02:00" level=info msg="set key resource: ../../kbs/config/kubernetes/overlays/s390x/key.bin"
[2024-07-26T01:19:21.367Z] time="2024-07-26T03:19:20+02:00" level=info msg="EnableKbsCustomizedPolicy: ../../kbs/sample_policies/allow_all.rego"
[2024-07-26T01:19:21.367Z] time="2024-07-26T03:19:20+02:00" level=info msg="EnableKbsCustomizedPolicy: ../../kbs/sample_policies/deny_all.rego"
[2024-07-26T01:19:21.367Z] === PAUSE TestLibvirtKbsKeyRelease
[2024-07-26T01:19:21.367Z] === CONT  TestLibvirtKbsKeyRelease
[2024-07-26T01:19:21.367Z] time="2024-07-26T03:19:20+02:00" level=info msg="Do test kbs key release failure case"
[2024-07-26T01:19:21.367Z] === RUN   TestLibvirtKbsKeyRelease/DoTestKbsKeyReleaseForFailure_test
[2024-07-26T01:19:53.633Z]     assessment_runner.go:265: Waiting for containers in pod: busybox-wget-failure are ready
[2024-07-26T01:19:56.375Z] === RUN   TestLibvirtKbsKeyRelease/DoTestKbsKeyReleaseForFailure_test/Kbs_key_release_is_failed
[2024-07-26T01:20:06.475Z] time="2024-07-26T03:20:05+02:00" level=info msg="PASS as failed to access key.bin: "
[2024-07-26T01:20:06.475Z]     assessment_runner.go:415: Output when execute test commands:
[2024-07-26T01:20:06.475Z] time="2024-07-26T03:20:05+02:00" level=info msg="Deleting pod busybox-wget-failure..."
[2024-07-26T01:20:10.755Z] time="2024-07-26T03:20:10+02:00" level=info msg="Pod busybox-wget-failure has been successfully deleted within 60s"
[2024-07-26T01:20:10.755Z] === NAME  TestLibvirtKbsKeyRelease
[2024-07-26T01:20:10.755Z]     libvirt_test.go:118: KBS with ibmse cases
[2024-07-26T01:20:10.755Z] time="2024-07-26T03:20:10+02:00" level=info msg="EnableKbsCustomizedPolicy: ../../kbs/sample_policies/allow_with_wrong_image_tag.rego"
[2024-07-26T01:20:11.031Z] time="2024-07-26T03:20:10+02:00" level=info msg="Do test kbs key release failure case"
[2024-07-26T01:20:11.031Z] === RUN   TestLibvirtKbsKeyRelease/DoTestKbsKeyReleaseForFailure_test#01
[2024-07-26T01:20:43.336Z]     assessment_runner.go:265: Waiting for containers in pod: busybox-wget-failure are ready
[2024-07-26T01:20:45.929Z] === RUN   TestLibvirtKbsKeyRelease/DoTestKbsKeyReleaseForFailure_test#01/Kbs_key_release_is_failed
[2024-07-26T01:20:56.098Z] time="2024-07-26T03:20:54+02:00" level=info msg="PASS as failed to access key.bin: "
[2024-07-26T01:20:56.098Z]     assessment_runner.go:415: Output when execute test commands:
[2024-07-26T01:20:56.098Z] time="2024-07-26T03:20:54+02:00" level=info msg="Deleting pod busybox-wget-failure..."
[2024-07-26T01:21:00.362Z] time="2024-07-26T03:20:59+02:00" level=info msg="Pod busybox-wget-failure has been successfully deleted within 60s"
[2024-07-26T01:21:00.362Z] time="2024-07-26T03:20:59+02:00" level=info msg="EnableKbsCustomizedPolicy: ../../kbs/sample_policies/allow_with_correct_claims.rego"
[2024-07-26T01:21:00.362Z] time="2024-07-26T03:21:00+02:00" level=info msg="Do test kbs key release"
[2024-07-26T01:21:00.362Z] === RUN   TestLibvirtKbsKeyRelease/KbsKeyReleasePod_test
[2024-07-26T01:21:27.114Z]     assessment_runner.go:265: Waiting for containers in pod: busybox-wget are ready
[2024-07-26T01:21:30.470Z] === RUN   TestLibvirtKbsKeyRelease/KbsKeyReleasePod_test/Kbs_key_release_is_successful
[2024-07-26T01:21:35.867Z] time="2024-07-26T03:21:35+02:00" level=info msg="Success to get key.bin: This is my cluster name: "
[2024-07-26T01:21:35.867Z]     assessment_runner.go:415: Output when execute test commands:This is my cluster name: 
[2024-07-26T01:21:35.867Z] time="2024-07-26T03:21:35+02:00" level=info msg="Deleting pod busybox-wget..."
[2024-07-26T01:21:41.266Z] time="2024-07-26T03:21:40+02:00" level=info msg="Pod busybox-wget has been successfully deleted within 60s"
[2024-07-26T01:21:41.266Z] --- PASS: TestLibvirtKbsKeyRelease (139.52s)
[2024-07-26T01:21:41.266Z]     --- PASS: TestLibvirtKbsKeyRelease/DoTestKbsKeyReleaseForFailure_test (49.58s)
[2024-07-26T01:21:41.266Z]         --- PASS: TestLibvirtKbsKeyRelease/DoTestKbsKeyReleaseForFailure_test/Kbs_key_release_is_failed (9.55s)
[2024-07-26T01:21:41.266Z]     --- PASS: TestLibvirtKbsKeyRelease/DoTestKbsKeyReleaseForFailure_test#01 (49.53s)
[2024-07-26T01:21:41.266Z]         --- PASS: TestLibvirtKbsKeyRelease/DoTestKbsKeyReleaseForFailure_test#01/Kbs_key_release_is_failed (9.51s)
[2024-07-26T01:21:41.266Z]     --- PASS: TestLibvirtKbsKeyRelease/KbsKeyReleasePod_test (40.33s)
[2024-07-26T01:21:41.266Z]         --- PASS: TestLibvirtKbsKeyRelease/KbsKeyReleasePod_test/Kbs_key_release_is_successful (5.29s)
[2024-07-26T01:21:41.266Z] PASS
[2024-07-26T01:21:41.266Z] time="2024-07-26T03:21:40+02:00" level=info msg="Deleting namespace 'coco-pp-e2e-test-958a7109'..."
[2024-07-26T01:21:51.359Z] time="2024-07-26T03:21:50+02:00" level=info msg="Namespace 'coco-pp-e2e-test-958a7109' has been successfully deleted within 60s"
[2024-07-26T01:21:55.631Z] peer-pods-ctlplane-0 deleted on local!
[2024-07-26T01:21:55.631Z] peer-pods-worker-0 deleted on local!
[2024-07-26T01:21:55.631Z] Deleting directory /root/.kcli/clusters/peer-pods
...

```

**Comment by liudalibj** [comment]
the e2e-test is failed after rebase codes with main brach,
the failed is related to https://github.com/confidential-containers/cloud-api-adaptor/pull/1931
`REGISTRY_CREDENTIAL_ENCODED` env is added, but the `auth.json` is missed.
https://github.com/confidential-containers/cloud-api-adaptor/blob/main/src/cloud-api-adaptor/test/e2e/assessment_runner.go#L195

**Comment by genjuro214** [comment]
@liudalibj , should we extract the KBS related code from `provision.go` and place it into a separate go file?

**Comment by liudalibj** [comment]
> @liudalibj , should we extract the KBS related code from `provision.go` and place it into a separate go file?

split kbs related codes to one file.

**Review by genjuro214 — APPROVED** [review]

**Review by huoqifeng — APPROVED** [review]
LGTM
thanks @liudalibj

**Pull request merged**
