### PR TITLE
e2e-test: ibmcloud se image test pipeline and one fix for ubuntu podvm image build

### PR DESCRIPTION
**Pull request by liudalibj**
- e2e-test: add nightly e2e-test for ibmcloud with secure execution
- podvm: try to fix podvm image build
fixes: #964 #969 
Signed-off-by: Da Li Liu <liudali@cn.ibm.com>

### CODE REVIEW

**Comment by liudalibj** [comment]
podvm image build in  github action is using docker buildx so we meet this issue in #969.
Try use one dummy.crt file to avoid the build break. Test locally with docker buildx:
```
 root@peerpod-se-image-vsi:~/cloud-api-adaptor/podvm# /usr/bin/docker buildx build --build-arg CLOUD_PROVIDER=generic --build-arg ARCH=s390x --build-arg UBUNTU_IMAGE_URL= --build-arg UBUNTU_IMAGE_CHECKSUM= --build-arg BINARIES_IMG=quay.io/liudalibj/podvm-binaries-ubuntu-s390x --build-arg BUILDER_IMG=quay.io/liudalibj/podvm-builder-ubuntu --file Dockerfile.podvm --platform linux/amd64 --provenance false --tag quay.io/liudalibj/podvm-generic-ubuntu-s390x:latest --push .
[+] Building 687.7s (20/20) FINISHED
 => [internal] load .dockerignore                                                                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                                                                          0.0s
 => [internal] load build definition from Dockerfile.podvm                                                                                                                                               0.0s
 => => transferring dockerfile: 2.58kB                                                                                                                                                                   0.0s
 => [internal] load metadata for quay.io/liudalibj/podvm-builder-ubuntu:latest                                                                                                                           1.2s
 => [internal] load metadata for quay.io/liudalibj/podvm-binaries-ubuntu-s390x:latest                                                                                                                    1.2s
 => [auth] liudalibj/podvm-builder-ubuntu:pull token for quay.io                                                                                                                                         0.0s
 => [auth] liudalibj/podvm-binaries-ubuntu-s390x:pull token for quay.io                                                                                                                                  0.0s
 => [internal] load build context                                                                                                                                                                        0.0s
 => => transferring context: 89B                                                                                                                                                                         0.0s
 => [podvm_binaries 1/1] FROM quay.io/liudalibj/podvm-binaries-ubuntu-s390x@sha256:d27235e27581a4e5c42ddd598945265e812b633e19cca9e42a4c161f80bb4b92                                                      0.0s
 => => resolve quay.io/liudalibj/podvm-binaries-ubuntu-s390x@sha256:d27235e27581a4e5c42ddd598945265e812b633e19cca9e42a4c161f80bb4b92                                                                     0.0s
 => CACHED [podvm_builder 1/9] FROM quay.io/liudalibj/podvm-builder-ubuntu@sha256:235bce82e5898217c1bf982631b5953dd31bf411712bbe7855cdd45e9e3e5295                                                       0.0s
 => => resolve quay.io/liudalibj/podvm-builder-ubuntu@sha256:235bce82e5898217c1bf982631b5953dd31bf411712bbe7855cdd45e9e3e5295                                                                            0.0s
 => [podvm_builder 2/9] RUN if [ -n "" ]; then       rm -rf cloud-api-adaptor &&       git clone  cloud-api-adaptor;    fi &&     if [ -n "" ]; then       cd cloud-api-adaptor &&       git fetch orig  0.2s
 => [podvm_builder 3/9] RUN ./cloud-api-adaptor/podvm/hack/cross-build-extras.sh                                                                                                                        15.4s
 => [podvm_builder 4/9] COPY --from=podvm_binaries /podvm-binaries.tar.gz /src/cloud-api-adaptor/podvm/files                                                                                             0.5s
 => [podvm_builder 5/9] RUN tar xvf /src/cloud-api-adaptor/podvm/files/podvm-binaries.tar.gz -C /src/cloud-api-adaptor/podvm/files                                                                       1.4s
 => [podvm_builder 6/9] COPY --from=podvm_binaries /pause-bundle.tar.gz /src/cloud-api-adaptor/podvm/files                                                                                               0.0s
 => [podvm_builder 7/9] RUN tar xvf /src/cloud-api-adaptor/podvm/files/pause-bundle.tar.gz -C /src/cloud-api-adaptor/podvm/files                                                                         0.1s
 => [podvm_builder 8/9] COPY files/*.crt /src/cloud-api-adaptor/podvm/files/                                                                                                                             0.0s
 => [podvm_builder 9/9] RUN cd cloud-api-adaptor/podvm &&      make BINARIES= PAUSE_BUNDLE= image                                                                                                      583.7s
 => [stage-2 1/1] COPY --from=podvm_builder /src/cloud-api-adaptor/podvm/output/*.qcow2 /                                                                                                                0.5s
 => exporting to image                                                                                                                                                                                  81.3s
 => => exporting layers                                                                                                                                                                                 31.0s
 => => exporting manifest sha256:d2322a730ef22b1e8a8a262d663d0394baacb3fb594fc0ca215ee58665698901                                                                                                        0.0s
 => => exporting config sha256:5805dd2c0fdc0017243e2af5100c55f954fadf617c778da67d0d7cdb4081ce62                                                                                                          0.0s
 => => pushing layers                                                                                                                                                                                   49.9s
 => => pushing manifest for quay.io/liudalibj/podvm-generic-ubuntu-s390x:latest@sha256:d2322a730ef22b1e8a8a262d663d0394baacb3fb594fc0ca215ee58665698901                                                  0.4s
 => [auth] liudalibj/podvm-generic-ubuntu-s390x:pull,push token for quay.io                                                                                                                              0.0s
root@peerpod-se-image-vsi:~/cloud-api-adaptor/podvm#
```

**Comment by liudalibj** [comment]
The new e2e-test pipeline for ibmcloud with secure execution 
https://github.com/liudalibj/cloud-api-adaptor/actions/runs/5011343888

**Comment by huoqifeng** [comment]
> The new e2e-test pipeline for ibmcloud with secure execution https://github.com/liudalibj/cloud-api-adaptor/actions/runs/5011343888

1 of the 3 actions failed in the job?

**Comment by liudalibj** [comment]
> > The new e2e-test pipeline for ibmcloud with secure execution https://github.com/liudalibj/cloud-api-adaptor/actions/runs/5011343888
> 
> 1 of the 3 actions failed in the job?

yeah, the failed one is because one timeout around build podvm. I am checking the root cause. it's should not effect the upstream code logical.

**Comment by liudalibj** [comment]
> > > The new e2e-test pipeline for ibmcloud with secure execution https://github.com/liudalibj/cloud-api-adaptor/actions/runs/5011343888
> > 
> > 
> > 1 of the 3 actions failed in the job?
> 
> yeah, the failed one is because one timeout around build podvm. I am checking the root cause. it's should not effect the upstream code logical.

I restart the internal job, it got a good result now https://sys-zaas-k8s-jenkins.swg-devops.com/job/cloud-api-adaptor-e2e-tests-opensource/176/console

**Review by stevenhorsman — APPROVED** [review]
This LGTM. Only minor comment is that it might be nice to add a bit more info to the body of the second commit to explain the need for the dummy crt file in the commit history if anyone needs to look at it?

**Comment by liudalibj** [comment]
> This LGTM. Only minor comment is that it might be nice to add a bit more info to the body of the second commit to explain the need for the dummy crt file in the commit history if anyone needs to look at it?

Thanks @stevenhorsman  the commit body updated.

**Review by huoqifeng — APPROVED** [review]
/lgtm
Thank you @liudalibj

**Pull request merged**
