### PR TITLE
ibmcloud: Embed pause container image

### LINKED ISSUE #196: Integrate pause container image in pod VM image
Pause container image is now embedded in the rootfs image of the upstream Kata Containers.

https://github.com/kata-containers/kata-containers/issues/4768

We also need to embed a pause image in the pod VM image.

### PR DESCRIPTION
**Pull request by yoheiueda**
Fixes #196

### CODE REVIEW

**Review by huoqifeng — APPROVED** [review]
LGTM, I guess other providers will be implemented by @bpradipt ?

**Comment by bpradipt** [comment]
@huoqifeng I wanted some discussion on this PR before merging. 
https://github.com/confidential-containers/cloud-api-adaptor/issues/196#issuecomment-1241506424

Sorry I should have put this on hold.

**Comment by yoheiueda** [comment]
I reopened the issue for discussion.

**Comment by huoqifeng** [comment]
@bpradipt @yoheiueda Let's discuss it next Wed... I'll write it down in the memo.

**Pull request merged**
