### PR TITLE
Azure: Add CI steps to update azure image id tag

### PR DESCRIPTION
**Pull request by kartikjoshi21**
Fixes: #1491

### CODE REVIEW

**Review by surajssd — APPROVED** [review]

**Comment by surajssd** [comment]
Once this file is actually updated from the pipeline the next step is to update the doc: https://github.com/confidential-containers/cloud-api-adaptor/tree/main/azure#build-caa-pod-vm-image to consume the above file.

**Review by mkulke — COMMENTED** [review]
Not sure I like the approach we're using here (littering the upstream git repo to store azure-specific pointers to a successful build). In any case we to include non-msft reviewers before we do that.

wouldn't `/CommunityGalleries/cocopodvm-d0e4f35f-5530-4b9c-8596-112487cdea85/Images/podvm_image0/Versions/latest` point to the latest successful build?

Alternatively I could think of an API query like this:

```bash
SUCCESS_TIME=$(curl \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/confidential-containers/cloud-api-adaptor/actions/workflows/azure-podvm-image-nightly-build.yml/runs?status=success" \
  | jq -r '.workflow_runs[0].updated_at')
IMAGE_VERSION=$(date -d "$SUCCESS_TIME" +%Y.%m.%d)
```

**Comment by bpradipt** [comment]
@kartikjoshi21 is this PR still valid ?

**Comment by surajssd** [comment]
Following works on both OSX and Linux:

```bash
SUCCESS_TIME=$(curl -s \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/confidential-containers/cloud-api-adaptor/actions/workflows/azure-podvm-image-nightly-build.yml/runs?status=success" \
  | jq -r '.workflow_runs[0].updated_at')

export IMAGE_VERSION=$(date -u -jf "%Y-%m-%dT%H:%M:%SZ" "$SUCCESS_TIME" "+%Y.%m.%d" 2>/dev/null || date -d "$SUCCESS_TIME" +%Y.%m.%d)
```

**Comment by kartikjoshi21** [comment]
> Following works on both OSX and Linux:
> 
> ```shell
> SUCCESS_TIME=$(curl -s \
>   -H "Accept: application/vnd.github+json" \
>   "https://api.github.com/repos/confidential-containers/cloud-api-adaptor/actions/workflows/azure-podvm-image-nightly-build.yml/runs?status=success" \
>   | jq -r '.workflow_runs[0].updated_at')
> 
> export IMAGE_VERSION=$(date -u -jf "%Y-%m-%dT%H:%M:%SZ" "$SUCCESS_TIME" "+%Y.%m.%d" 2>/dev/null || date -d "$SUCCESS_TIME" +%Y.%m.%d)
> ```

Thanks @surajssd @mkulke . We can close this one. @surajssd can you help to add this instruction to documentation in your current doc PR ? Thanks

**Comment by kartikjoshi21** [comment]
Added to the documentation 
https://github.com/confidential-containers/confidentialcontainers.org/pull/20

Closing this one

**Pull request closed without merging**
