### PR TITLE
test/e2e:fix the bad workflows after we are in new file structure

### PR DESCRIPTION
**Pull request by chathuryaadapa**
Updated src/cloud-api-adaptor/test/provisioner/provision.go file for deploying and undeploying peerpod-ctrl
fixes: 1767

### CODE REVIEW

**Comment by lysliu** [comment]
@liudalibj please help to review this

**Review by liudalibj — COMMENTED** [review]
The path for peerpod-ctrl is correct from `run test-e2e` view.
We run `make test-e2e` under `src/cloud-api-adaptor` folder so when we try to install/uninstall peerpod-ctrl, we need `../peerpod-ctrl` path.

**Comment by liudalibj** [comment]
With this PR, the `test_e2e_libvirt` workflow will be failed.

**Comment by liudalibj** [comment]
> Updated src/cloud-api-adaptor/test/provisioner/provision.go file for deploying and undeploying peerpod-ctrl fixes: 1767

@chathuryaadapa would you like add more details, what's the reproduce steps?

**Pull request closed without merging**
