### PR TITLE
controllers: refactor and add verify checks

### PR DESCRIPTION
**Pull request by Amulyam24**
- This PR adds verify targets to check if go modules and manifests are up to date
- It also refactor the verify targets in peerpodconfig-ctrl and add the checks to the controllers workflow

Fixes: #1349

### CODE REVIEW

**Review by bpradipt — COMMENTED** [review]
@Amulyam24 did you run the updated workflow locally once using https://github.com/nektos/act ?
Overall the changes looks good to me.

**Comment by Amulyam24** [comment]
> @Amulyam24 did you run the updated workflow locally once using https://github.com/nektos/act ?
> Overall the changes looks good to me.

yes @bpradipt, tested it locally with a successful run.

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @Amulyam24

**Review by snir911 — APPROVED** [review]
LGTM thanks!

**Pull request merged**
