### PR TITLE
ibmcloud: Bug fix to catch PodVm Failure

### PR DESCRIPTION
**Pull request by sudharshanibm3**
Added code to catch PodVM Failure error

Fixes: #930, #1004

### CODE REVIEW

**Comment by sudharshanibm3** [comment]
Test Log before Bug Fix:

```
=== RUN   TestCreatePeerPodWithJob/JobPeerPod_test/Job_has_been_created
--- FAIL: TestCreatePeerPodWithJob (600.14s)
    --- FAIL: TestCreatePeerPodWithJob/JobPeerPod_test (600.14s)
        --- FAIL: TestCreatePeerPodWithJob/JobPeerPod_test/Job_has_been_created (0.06s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2785359]
goroutine 1744 [running]:
testing.tRunner.func1.2({0x2a57da0, 0x40ad500})
	/usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0x2a57da0, 0x40ad500})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/confidential-containers/cloud-api-adaptor/test/e2e.getSuccessfulAndErroredPods({_, _}, _, {_, _}, {{{0x0, 0x0}, {0x0, 0x0}}, {{0xc00255a380, ...}, ...}, ...})
	/home/jenkins/agent/workspace/cloud-api-adaptor-e2e-tests-opensource/cloud-api-adaptor/test/e2e/common_suite_test.go:314 +0x339
github.com/confidential-containers/cloud-api-adaptor/test/e2e.(*testCase).run.func2({0x313edd8, 0xc000226000}, 0xc002193a00, 0xc00011ff10?)
	/home/jenkins/agent/workspace/cloud-api-adaptor-e2e-tests-opensource/cloud-api-adaptor/test/e2e/common_suite_test.go:140 +0x1f1
sigs.k8s.io/e2e-framework/pkg/env.(*testEnv).executeSteps(0xc0003f5900, {0x313edd8?, 0xc000226000?}, 0x3b49d38?, {0xc000653f50?, 0x1, 0xfe11a5?})
	/home/jenkins/go/pkg/mod/sigs.k8s.io/e2e-framework@v0.1.0/pkg/env/env.go:421 +0xa3
sigs.k8s.io/e2e-framework/pkg/env.(*testEnv).execFeature.func1.1(0xc002193a00)
	/home/jenkins/go/pkg/mod/sigs.k8s.io/e2e-framework@v0.1.0/pkg/env/env.go:452 +0xad
testing.tRunner(0xc002193a00, 0xc001140de0)
	/usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1629 +0x3ea
FAIL	github.com/confidential-containers/cloud-api-adaptor/test/e2e	3079.793s
FAIL
```

Test Log After Bug Fix:
```
=== RUN   TestCreatePeerPodWithJob
=== RUN   TestCreatePeerPodWithJob/JobPeerPod_test
    common_suite_test.go:117: timed out waiting for the condition
=== RUN   TestCreatePeerPodWithJob/JobPeerPod_test/Job_has_been_created
    common_suite_test.go:142: Failed to Create PodVM
time="2023-06-19T19:31:09+05:30" level=info msg="Deleting Job... job-pi"
time="2023-06-19T19:31:09+05:30" level=info msg="Deleting pods created by job... job-pi-jr2sx"
--- FAIL: TestCreatePeerPodWithJob (602.11s)
    --- FAIL: TestCreatePeerPodWithJob/JobPeerPod_test (602.11s)
        --- FAIL: TestCreatePeerPodWithJob/JobPeerPod_test/Job_has_been_created (0.37s)
FAIL
```

**Comment by stevenhorsman** [comment]
If we get into this failed state do/can we show the describe events of the pod and/or caa so we can try and work out what the  cause of the issue is, otherwise it doesn't help much with debug?

**Comment by sudharshanibm3** [comment]
Hi @stevenhorsman ,
Ideally all test case must return `timed out waiting for the condition` if PODVM fails to load 
But in Job test cases-we dont have indiduval wait time for each pod as well as we are tracking on both Error and Completed pods. So added a condition now, where the Pod stucks in ContainerCreating state for a long time.

**Review by stevenhorsman — APPROVED** [review]
Looks okay to me

**Review by liudalibj — APPROVED** [review]
LGTM, Thanks for the fix @sudharshanibm3

**Pull request merged**
