### PR TITLE
ibmcloud: Allow import of qcow2 file

### PR DESCRIPTION
**Pull request by stevenhorsman**
Allow import.sh to upload a direct qcow2 file to ibm cloud

Fixes: #661

### CODE REVIEW

**Review by jtumber-ibm — APPROVED** [review]
lgtm, thanks @stevenhorsman

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @stevenhorsman

**Comment by stevenhorsman** [comment]
Thanks for the reviews. I'll double check it still works manually for both scenarios since I did the updates before I merge it :)

**Comment by stevenhorsman** [comment]
Running this against a container image:
```
./import.sh localhost/podvm_ibmcloud_s390x:latest ca-tor --instance XXX --bucket XXX
...
Downloading file from image localhost/podvm_ibmcloud_s390x:latest
Uploading file podvm-5d18b67-s390x.qcow2
...
OK
Successfully uploaded 'podvm-5d18b67-s390x.qcow2' to bucket 'xxx.
Created image podvm-5d18b67-s390x with id xxx
Image podvm-5d18b67-s390x with id xxx is available
OK
```
And verifying that the VPC image was created correctly:
```
# ibmcloud is images --visibility=private
Listing images in all resource groups and region ca-tor under account Steven Horsman's Account as user steven@uk.ibm.com...
ID                                          Name                           Status      Arch    OS name              OS version                              File size(GB)   Visibility   Owner type   Encryption   Resource group   Catalog Offering
xxx   podvm-5d18b67-s390x            available   s390x   ubuntu-20-04-s390x   20.04 LTS Focal Fossa Minimal Install   1               private      user         none         default          -
```

Running this directly against a qcow2:
```
./import.sh povm-4d123sd-s390x.qcow2 ca-tor --instance xxx --bucket xxx
...
Uploading file povm-4d123sd-s390x.qcow2
Uploading to 01000186-a2f8-e357-2ab9-27d29cc9f806
...
OK
Successfully uploaded 'povm-4d123sd-s390x.qcow2' to bucket 'xxx.
Created image povm-4d123sd-s390x with id xxx
Image povm-4d123sd-s390x with id xxx is available
OK
Delete 'povm-4d123sd-s390x.qcow2' from bucket 'xxx' ran successfully.
```
And checking that created a custom image:
```
# ibmcloud is images --visibility=private
Listing images in all resource groups and region ca-tor under account Steven Horsman's Account as user steven@uk.ibm.com...
ID                                          Name                           Status      Arch    OS name              OS version                              File size(GB)   Visibility   Owner type   Encryption   Resource group   Catalog Offering
xxx   povm-4d123sd-s390x             available   s390x   ubuntu-20-04-s390x   20.04 LTS Focal Fossa Minimal Install   1               private      user         none         default          -
```

Showing that both cases still work, so I think this can be merged now.

**Pull request merged**
