### PR TITLE
versions: Bump golang

### PR DESCRIPTION
**Pull request by stevenhorsman**
- Bump to go 1.20.12 to resolve https://pkg.go.dev/vuln/GO-2023-2382

### CODE REVIEW

**Review by tumberino — APPROVED** [review]
lgtm

**Review by bpradipt — COMMENTED** [review]
/lgtm

**Comment by stevenhorsman** [comment]
> @stevenhorsman have you used hack/update-go-container.sh to bump the version?

Yes - that's where all the checksums automatically were gen'd by

> And next you will send a PR to update Dockerfile?

Sorry, which Dockerfile? Did I miss something?

**Comment by bpradipt** [comment]
> @bpradipt - sorry Pradipta, I think you left a comment, rather than approval, so it still needs a second green tick. Thanks!

Yeah sorry about it.

**Comment by stevenhorsman** [comment]
Adding hold label until I understand from Wainer what I've missed

**Comment by wainersm** [comment]
> Adding hold label until I understand from Wainer what I've missed

I was talking about https://github.com/confidential-containers/cloud-api-adaptor/blob/main/Dockerfile#L2 .

**Comment by stevenhorsman** [comment]
> I was talking about https://github.com/confidential-containers/cloud-api-adaptor/blob/main/Dockerfile#L2 .

Okay, so something that has to be done as follow up and the image won't be build yet. Understood and thanks for the reminder (that it looks like we've forgotten the last few times).

**Review by wainersm — APPROVED** [review]
Thanks @stevenhorsman !

**Comment by stevenhorsman** [comment]
> > I was talking about https://github.com/confidential-containers/cloud-api-adaptor/blob/main/Dockerfile#L2 .
> 
> Okay, so something that has to be done as follow up and the image won't be build yet. Understood and thanks for the reminder (that it looks like we've forgotten the last few times).

Now the base image has been built and pushed to quay.io - I've created https://github.com/confidential-containers/cloud-api-adaptor/pull/1621 to use it

**Pull request merged**
