### PR TITLE
Update to the latest CCv0-peerpod branch

### PR DESCRIPTION
**Pull request by yoheiueda**
The latest [CCv0-peerpod branch](https://github.com/yoheiueda/kata-containers/tree/CCv0-peerpod) has the following code changes.

* `go.sum` is updated, since the upstream CCv0 branch has been rebased to the latest main branch.
* option name in `config.toml` is changed from remote_hypervisor to remote_hypervisor_socket based on a PR comment

https://github.com/kata-containers/kata-containers/pull/3697#discussion_r908641458

This PR includes necessary changes to synchronized with the latest CCv0-peerpod branch.

### CODE REVIEW

**Comment by stevenhorsman** [comment]
So looking at the logs I see:
```
time="2022-07-08T14:28:04.015053819+05:30" level=error msg="Create new sandbox failed" error="Missing kernel path" name=containerd-shim-v2 pid=18625 sandbox=90cbf25f1b1cd5a52aea231b6eaef42bfee8e8110090f2745dd21dc04412dc25 source=virtcontainers subsystem=sandbox
```
There has been a refactor of this code recently to add darwin support, so my theory is that in the re-base/update we've pulled in:
https://github.com/yoheiueda/kata-containers/blob/9253873a9e53040d0f6c7d5a15fd418a2e569e99/src/runtime/virtcontainers/hypervisor_config_linux.go#L16-L18
which was previously not being run out or something? @yoheiueda

**Comment by yoheiueda** [comment]
@stevenhorsman Thank you very much for testing.

I updated the CCv0-peerpod branch to set dummy values to avoid the checks in `validateHypervisorConfig`.
https://github.com/yoheiueda/kata-containers/blob/8f176024bcd7d78b81439df75824e068b31eaddd/src/runtime/pkg/katautils/config.go#L996-L1000

**Comment by stevenhorsman** [comment]
> @stevenhorsman Thank you very much for testing.
> 
> I updated the CCv0-peerpod branch to set dummy values to avoid the checks in `validateHypervisorConfig`. https://github.com/yoheiueda/kata-containers/blob/8f176024bcd7d78b81439df75824e068b31eaddd/src/runtime/pkg/katautils/config.go#L996-L1000

Thanks, I'll re-run the tests now :)

**Review by stevenhorsman — APPROVED** [review]
The e2e tests pass for me now. Thanks Yohei!

**Comment by yoheiueda** [comment]
Thank you for the confirmation.

**Pull request merged**
