### PR TITLE
operator: pod image multi-arch support

### PR DESCRIPTION
**Pull request by liudalibj**
- build out s390x cloud-api-adaptor binary via cross go build
- build s390x cloud-api-adaptor pod image
Fixes: #533
Signed-off-by: Da Li Liu <liudali@cn.ibm.com>

### CODE REVIEW

**Comment by liudalibj** [comment]
The full build logs with this PR, after I set the `registry=liudali/caa-dev`
```
root@csi-x86-worker:~/cloud-api-adaptor# CLOUD_PROVIDER=ibmcloud make image
Built out multi-arch binaries for cloud-api-adaptor
-rwxr-xr-x 1 root root 41M Jan 18 10:14 cloud-api-adaptor-s390x
-rwxr-xr-x 1 root root 39M Jan 18 10:14 cloud-api-adaptor-x86_64
hack/build.sh
~/cloud-api-adaptor ~/cloud-api-adaptor
Building cloud-api-adaptor ibmcloud image for linux/amd64
[+] Building 4.1s (11/11) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                                            0.0s
 => => transferring dockerfile: 752B                                                                                                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/fedora:36                                                                                                                                                                                    1.2s
 => [auth] library/fedora:pull token for registry-1.docker.io                                                                                                                                                                                   0.0s
 => [1/4] FROM docker.io/library/fedora:36@sha256:17ab257e353f7e0247ce4b1a6ac7a4dd372cf217e532f27d67feb876a53af471                                                                                                                              0.0s
 => => resolve docker.io/library/fedora:36@sha256:17ab257e353f7e0247ce4b1a6ac7a4dd372cf217e532f27d67feb876a53af471                                                                                                                              0.0s
 => [internal] load build context                                                                                                                                                                                                               1.1s
 => => transferring context: 40.10MB                                                                                                                                                                                                            1.1s
 => CACHED [2/4] RUN if [ "ibmcloud" = "libvirt" ] ; then dnf install -y libvirt-libs genisoimage /usr/bin/ssh && dnf clean all; fi                                                                                                             0.0s
 => CACHED [3/4] COPY cloud-api-adaptor-x86_64 /usr/local/bin/cloud-api-adaptor-ibmcloud                                                                                                                                                        0.0s
 => CACHED [4/4] COPY entrypoint.sh /usr/local/bin/entrypoint.sh                                                                                                                                                                                0.0s
 => exporting to docker image format                                                                                                                                                                                                            1.6s
 => => exporting layers                                                                                                                                                                                                                         0.0s
 => => exporting manifest sha256:db22d221ef526fcf3aa21637687fe661cdb31723580643991ea38b843035b91b                                                                                                                                               0.0s
 => => exporting config sha256:bcb4be809100c2d97e47615b6efa625549ed22895e676a2d4067269728323f07                                                                                                                                                 0.0s
 => => sending tarball                                                                                                                                                                                                                          1.6s
 => importing to docker                                                                                                                                                                                                                         0.0s
The push refers to repository [docker.io/liudali/cca-dev]
1f309f6a2eb7: Layer already exists
473aa28c5e9d: Layer already exists
5f70bf18a086: Layer already exists
de059ad30e8f: Layer already exists
x86_64-2023011810141674036862: digest: sha256:95a91fbee9ed597334aa4934c7fba49018de5ae780aedad0f7d4f9d26e2eafc8 size: 1155
Building cloud-api-adaptor ibmcloud image for linux/s390x
[+] Building 3.4s (10/10) FINISHED
 => [internal] load .dockerignore                                                                                                                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                                                                                                                 0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                                                            0.0s
 => => transferring dockerfile: 752B                                                                                                                                                                                                            0.0s
 => [internal] load metadata for docker.io/library/fedora:36                                                                                                                                                                                    0.5s
 => [1/4] FROM docker.io/library/fedora:36@sha256:17ab257e353f7e0247ce4b1a6ac7a4dd372cf217e532f27d67feb876a53af471                                                                                                                              0.0s
 => => resolve docker.io/library/fedora:36@sha256:17ab257e353f7e0247ce4b1a6ac7a4dd372cf217e532f27d67feb876a53af471                                                                                                                              0.0s
 => [internal] load build context                                                                                                                                                                                                               1.1s
 => => transferring context: 42.00MB                                                                                                                                                                                                            1.1s
 => CACHED [2/4] RUN if [ "ibmcloud" = "libvirt" ] ; then dnf install -y libvirt-libs genisoimage /usr/bin/ssh && dnf clean all; fi                                                                                                             0.0s
 => CACHED [3/4] COPY cloud-api-adaptor-s390x /usr/local/bin/cloud-api-adaptor-ibmcloud                                                                                                                                                         0.0s
 => CACHED [4/4] COPY entrypoint.sh /usr/local/bin/entrypoint.sh                                                                                                                                                                                0.0s
 => exporting to docker image format                                                                                                                                                                                                            1.7s
 => => exporting layers                                                                                                                                                                                                                         0.0s
 => => exporting manifest sha256:9feaf52272583c2f921d5c6fae89da34be5229a1d26b574d07412b586d4a7d92                                                                                                                                               0.0s
 => => exporting config sha256:07dc8bf1e03be6a1b5590afb01b38bc6344b98069bb45151db6e6540301dec57                                                                                                                                                 0.0s
 => => sending tarball                                                                                                                                                                                                                          1.6s
 => importing to docker                                                                                                                                                                                                                         0.0s
The push refers to repository [docker.io/liudali/cca-dev]
85cd7426924b: Layer already exists
40ae77ecf5c8: Layer already exists
5f70bf18a086: Layer already exists
61c0926d1911: Layer already exists
s390x-2023011810141674036862: digest: sha256:25825f58c6ad9f2b3bbc5e699970cc36ada5f4c2ed71a1b02234ab925c1c0758 size: 1155
Created manifest list docker.io/liudali/cca-dev:2023011810141674036862
Created manifest list docker.io/liudali/cca-dev:latest
sha256:7aa21bc64f9dbada2e5940ee1bfc581cfd251cb938e4c9f2b9cbe83507f622a1
sha256:7aa21bc64f9dbada2e5940ee1bfc581cfd251cb938e4c9f2b9cbe83507f622a1
~/cloud-api-adaptor
root@csi-x86-worker:~/cloud-api-adaptor#
```

**Comment by liudalibj** [comment]
Because it failed to build out related multi-arch binaries inside the builder, I removed the builder section in Dockerfile.
If we still want to use builder section inside the Docker, need more time to investigate why it doesn't work.

**Comment by jtumber-ibm** [comment]
I'll take a quick look at using the builder step in multi-arch. Do you have any logs from the failed attempts?

**Comment by liudalibj** [comment]
> I'll take a quick look at using the builder step in multi-arch. Do you have any logs from the failed attempts?

```
root@csi-x86-worker:~/cloud-api-adaptor# CLOUD_PROVIDER=ibmcloud make image
hack/build.sh
~/cloud-api-adaptor ~/cloud-api-adaptor
Building cloud-api-adaptor ibmcloud image for linux/amd64
[+] Building 2.8s (17/17) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                                            0.0s
 => => transferring dockerfile: 814B                                                                                                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/fedora:36                                                                                                                                                                                    0.5s
 => [internal] load metadata for docker.io/library/golang:1.19.3                                                                                                                                                                                0.5s
 => [internal] load build context                                                                                                                                                                                                               0.4s
 => => transferring context: 696.67kB                                                                                                                                                                                                           0.4s
 => [m-builder 1/6] FROM docker.io/library/golang:1.19.3@sha256:10e3c0f39f8e237baa5b66c5295c578cac42a99536cc9333d8505324a82407d9                                                                                                                0.0s
 => => resolve docker.io/library/golang:1.19.3@sha256:10e3c0f39f8e237baa5b66c5295c578cac42a99536cc9333d8505324a82407d9                                                                                                                          0.0s
 => [stage-1 1/4] FROM docker.io/library/fedora:36@sha256:17ab257e353f7e0247ce4b1a6ac7a4dd372cf217e532f27d67feb876a53af471                                                                                                                      0.0s
 => => resolve docker.io/library/fedora:36@sha256:17ab257e353f7e0247ce4b1a6ac7a4dd372cf217e532f27d67feb876a53af471                                                                                                                              0.0s
 => CACHED [stage-1 2/4] RUN if [ "ibmcloud" = "libvirt" ] ; then dnf install -y libvirt-libs genisoimage /usr/bin/ssh && dnf clean all; fi                                                                                                     0.0s
 => CACHED [m-builder 2/6] COPY . cloud-api-adaptor                                                                                                                                                                                             0.0s
 => CACHED [m-builder 3/6] RUN git clone -b CCv0 https://github.com/kata-containers/kata-containers                                                                                                                                             0.0s
 => CACHED [m-builder 4/6] WORKDIR cloud-api-adaptor                                                                                                                                                                                            0.0s
 => CACHED [m-builder 5/6] RUN if [ "ibmcloud" = "libvirt" ] ; then apt-get update -y && apt-get install -y libvirt-dev; fi                                                                                                                     0.0s
 => CACHED [m-builder 6/6] RUN make cloud-api-adaptor                                                                                                                                                                                           0.0s
 => CACHED [stage-1 3/4] COPY --from=m-builder /go/cloud-api-adaptor/cloud-api-adaptor-x86_64 /usr/local/bin/cloud-api-adaptor-ibmcloud                                                                                                         0.0s
 => CACHED [stage-1 4/4] COPY --from=m-builder /go/cloud-api-adaptor/entrypoint.sh /usr/local/bin/entrypoint.sh                                                                                                                                 0.0s
 => exporting to docker image format                                                                                                                                                                                                            1.7s
 => => exporting layers                                                                                                                                                                                                                         0.0s
 => => exporting manifest sha256:629dcc4f3fa48effc8842a37c7d0cfa599d94d8193f8ce82655d5bd37e8cf1dd                                                                                                                                               0.0s
 => => exporting config sha256:2549efc5a96ed1bbf360516560071f2c6c6aad4ec3e53c1c5bde35a6a585e566                                                                                                                                                 0.0s
 => => sending tarball                                                                                                                                                                                                                          1.7s
 => importing to docker                                                                                                                                                                                                                         0.0s
The push refers to repository [docker.io/liudali/cca-dev]
87876376c3a3: Layer already exists
2086de02f196: Layer already exists
5f70bf18a086: Layer already exists
de059ad30e8f: Layer already exists
x86_64-2023011807391674027571: digest: sha256:85773a1b27f6052ba18fa5d43f707dde53bae6bdcd36f68d9399ffb48d3986bc size: 1155
Building cloud-api-adaptor ibmcloud image for linux/s390x
[+] Building 15.2s (13/15)
 => [internal] load .dockerignore                                                                                                                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                                                                                                                 0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                                                            0.0s
 => => transferring dockerfile: 814B                                                                                                                                                                                                            0.0s
 => [internal] load metadata for docker.io/library/fedora:36                                                                                                                                                                                    0.6s
 => [internal] load metadata for docker.io/library/golang:1.19.3                                                                                                                                                                                0.5s
 => [internal] load build context                                                                                                                                                                                                               0.4s
 => => transferring context: 696.67kB                                                                                                                                                                                                           0.4s
 => [stage-1 1/4] FROM docker.io/library/fedora:36@sha256:17ab257e353f7e0247ce4b1a6ac7a4dd372cf217e532f27d67feb876a53af471                                                                                                                      0.0s
 => => resolve docker.io/library/fedora:36@sha256:17ab257e353f7e0247ce4b1a6ac7a4dd372cf217e532f27d67feb876a53af471                                                                                                                              0.0s
 => [m-builder 1/6] FROM docker.io/library/golang:1.19.3@sha256:10e3c0f39f8e237baa5b66c5295c578cac42a99536cc9333d8505324a82407d9                                                                                                                0.0s
 => => resolve docker.io/library/golang:1.19.3@sha256:10e3c0f39f8e237baa5b66c5295c578cac42a99536cc9333d8505324a82407d9                                                                                                                          0.0s
 => CACHED [stage-1 2/4] RUN if [ "ibmcloud" = "libvirt" ] ; then dnf install -y libvirt-libs genisoimage /usr/bin/ssh && dnf clean all; fi                                                                                                     0.0s
 => CACHED [m-builder 2/6] COPY . cloud-api-adaptor                                                                                                                                                                                             0.0s
 => CACHED [m-builder 3/6] RUN git clone -b CCv0 https://github.com/kata-containers/kata-containers                                                                                                                                             0.0s
 => CACHED [m-builder 4/6] WORKDIR cloud-api-adaptor                                                                                                                                                                                            0.0s
 => CACHED [m-builder 5/6] RUN if [ "ibmcloud" = "libvirt" ] ; then apt-get update -y && apt-get install -y libvirt-dev; fi                                                                                                                     0.0s
 => ERROR [m-builder 6/6] RUN make cloud-api-adaptor                                                                                                                                                                                           14.1s
------
 > [m-builder 6/6] RUN make cloud-api-adaptor:
#0 0.607 go: downloading golang.org/x/sys v0.0.0-20220722155257-8c9f86f7a55f
#0 0.808 go: downloading github.com/containerd/containerd v1.6.6
#0 0.852 go: downloading github.com/containerd/ttrpc v1.1.0
#0 1.023 go: downloading github.com/kata-containers/kata-containers/src/runtime v0.0.0-20220913141151-9b49a6ddc6fd
#0 1.026 go: downloading github.com/vmware/govmomi v0.29.0
#0 1.202 go: downloading github.com/avast/retry-go/v4 v4.3.2
#0 1.204 go: downloading github.com/containers/podman/v4 v4.2.0
#0 1.298 go: downloading github.com/gogo/protobuf v1.3.2
#0 1.378 go: downloading google.golang.org/grpc v1.47.0
#0 1.577 go: downloading k8s.io/cri-api v0.23.1
#0 1.614 go: downloading github.com/opencontainers/runtime-spec v1.0.3-0.20211214071223-8958f93039ab
#0 1.657 go: downloading github.com/vishvananda/netlink v1.1.1-0.20220115184804-dd687eb2f2d4
#0 1.718 go: downloading github.com/coreos/go-iptables v0.6.0
#0 1.901 go: downloading github.com/containernetworking/plugins v1.1.1
#0 1.907 go: downloading github.com/vishvananda/netns v0.0.0-20210104183010-2eb08e3e575f
#0 1.929 -> unzip /go/pkg/mod/cache/download/github.com/vishvananda/netns/@v/v0.0.0-20210104183010-2eb08e3e575f.zip: zip: checksum error
#0 9.094 go: downloading golang.org/x/sys v0.0.0-20220722155257-8c9f86f7a55f
#0 9.124 go: downloading github.com/IBM/go-sdk-core/v5 v5.6.3
#0 9.478 go: downloading github.com/IBM/vpc-go-sdk v1.0.1
#0 9.496 go: downloading github.com/containerd/containerd v1.6.6
#0 9.622 go: downloading github.com/containerd/ttrpc v1.1.0
#0 9.622 go: downloading github.com/kata-containers/kata-containers/src/runtime v0.0.0-20220913141151-9b49a6ddc6fd
#0 9.713 go: downloading google.golang.org/grpc v1.47.0
#0 9.737 -> unzip /go/pkg/mod/cache/download/github.com/containerd/ttrpc/@v/v1.1.0.zip: zip: checksum error
#0 9.827 go: downloading github.com/vmware/govmomi v0.29.0
#0 9.971 go: downloading github.com/vishvananda/netlink v1.1.1-0.20220115184804-dd687eb2f2d4
#0 10.01 go: downloading github.com/avast/retry-go/v4 v4.3.2
#0 10.07 -> unzip /go/pkg/mod/cache/download/github.com/avast/retry-go/v4/@v/v4.3.2.zip: zip: checksum error
#0 10.09 go: downloading github.com/containers/podman/v4 v4.2.0
#0 10.10 go: downloading github.com/gogo/protobuf v1.3.2
#0 10.11 go: downloading k8s.io/cri-api v0.23.1
#0 10.11 go: downloading github.com/opencontainers/runtime-spec v1.0.3-0.20211214071223-8958f93039ab
#0 10.20 go: downloading github.com/containernetworking/plugins v1.1.1
#0 10.27 go: downloading github.com/coreos/go-iptables v0.6.0
#0 11.41 pkg/adaptor/hypervisor/ibmcloud/vpcv1.go:8:2: zip: checksum error
#0 11.41 pkg/adaptor/hypervisor/ibmcloud/service.go:20:2: github.com/IBM/vpc-go-sdk@v1.0.1: read "https:/proxy.golang.org/@v/v1.0.1.zip": local error: tls: bad record MAC
#0 11.41 pkg/adaptor/proxy/service.go:12:2: unzip /go/pkg/mod/cache/download/github.com/avast/retry-go/v4/@v/v4.3.2.zip: zip: checksum error
#0 11.41 pkg/adaptor/proxy/service.go:14:2: github.com/containerd/containerd@v1.6.6: read "https:/proxy.golang.org/@v/v1.6.6.zip": local error: tls: bad record MAC
#0 11.41 pkg/util/agentproto/redirector.go:13:2: unzip /go/pkg/mod/cache/download/github.com/containerd/ttrpc/@v/v1.1.0.zip: zip: checksum error
#0 11.41 pkg/util/netops/netops.go:20:2: zip: checksum error
#0 11.41 pkg/adaptor/proxy/service.go:15:2: github.com/containers/podman/v4@v4.2.0: read "https:/proxy.golang.org/@v/v4.2.0.zip": local error: tls: bad record MAC
#0 11.41 proto/podvminfo/podvminfo.pb.go:10:2: github.com/gogo/protobuf@v1.3.2: Get "https://proxy.golang.org/github.com/gogo/protobuf/@v/v1.3.2.zip": local error: tls: bad record MAC
#0 11.41 pkg/util/agentproto/redirector.go:14:2: github.com/gogo/protobuf@v1.3.2: Get "https://proxy.golang.org/github.com/gogo/protobuf/@v/v1.3.2.zip": local error: tls: bad record MAC
#0 11.41 pkg/adaptor/hypervisor/ibmcloud/server.go:19:2: github.com/kata-containers/kata-containers/src/runtime@v0.0.0-20220913141151-9b49a6ddc6fd: read "https:/proxy.golang.org/@v/v0.0.0-20220913141151-9b49a6ddc6fd.zip": local error: tls: bad record MAC
#0 11.41 pkg/util/agentproto/redirector.go:15:2: github.com/kata-containers/kata-containers/src/runtime@v0.0.0-20220913141151-9b49a6ddc6fd: read "https:/proxy.golang.org/@v/v0.0.0-20220913141151-9b49a6ddc6fd.zip": local error: tls: bad record MAC
#0 11.41 pkg/util/agentproto/redirector.go:17:2: github.com/kata-containers/kata-containers/src/runtime@v0.0.0-20220913141151-9b49a6ddc6fd: read "https:/proxy.golang.org/@v/v0.0.0-20220913141151-9b49a6ddc6fd.zip": local error: tls: bad record MAC
#0 11.41 pkg/forwarder/interceptor/interceptor.go:16:2: zip: checksum error
#0 11.41 pkg/util/netops/netops.go:16:2: zip: checksum error
#0 11.41 pkg/adaptor/hypervisor/vsphere/server.go:14:2: github.com/vmware/govmomi@v0.29.0: read "https:/proxy.golang.org/@v/v0.29.0.zip": local error: tls: bad record MAC
#0 11.41 pkg/adaptor/hypervisor/vsphere/vsphere.go:15:2: github.com/vmware/govmomi@v0.29.0: read "https:/proxy.golang.org/@v/v0.29.0.zip": local error: tls: bad record MAC
#0 11.41 pkg/adaptor/hypervisor/vsphere/vsphere.go:16:2: github.com/vmware/govmomi@v0.29.0: read "https:/proxy.golang.org/@v/v0.29.0.zip": local error: tls: bad record MAC
#0 11.41 pkg/adaptor/hypervisor/vsphere/vsphere.go:17:2: github.com/vmware/govmomi@v0.29.0: read "https:/proxy.golang.org/@v/v0.29.0.zip": local error: tls: bad record MAC
#0 11.41 pkg/adaptor/hypervisor/vsphere/vsphere.go:18:2: github.com/vmware/govmomi@v0.29.0: read "https:/proxy.golang.org/@v/v0.29.0.zip": local error: tls: bad record MAC
#0 11.41 pkg/adaptor/hypervisor/vsphere/vsphere.go:19:2: github.com/vmware/govmomi@v0.29.0: read "https:/proxy.golang.org/@v/v0.29.0.zip": local error: tls: bad record MAC
#0 11.41 pkg/adaptor/hypervisor/vsphere/vsphere.go:20:2: github.com/vmware/govmomi@v0.29.0: read "https:/proxy.golang.org/@v/v0.29.0.zip": local error: tls: bad record MAC
#0 11.41 pkg/adaptor/hypervisor/vsphere/vsphere.go:21:2: github.com/vmware/govmomi@v0.29.0: read "https:/proxy.golang.org/@v/v0.29.0.zip": local error: tls: bad record MAC
#0 11.41 pkg/adaptor/hypervisor/vsphere/vsphere.go:22:2: github.com/vmware/govmomi@v0.29.0: read "https:/proxy.golang.org/@v/v0.29.0.zip": local error: tls: bad record MAC
#0 11.41 cmd/starter.go:13:2: golang.org/x/sys@v0.0.0-20220722155257-8c9f86f7a55f: read "https:/proxy.golang.org/@v/v0.0.0-20220722155257-8c9f86f7a55f.zip": local error: tls: bad record MAC
#0 11.41 pkg/adaptor/proxy/proxy.go:20:2: google.golang.org/grpc@v1.47.0: read "https:/proxy.golang.org/@v/v1.47.0.zip": local error: tls: bad record MAC
#0 11.41 pkg/adaptor/hypervisor/ibmcloud/podvminfo.go:10:2: google.golang.org/grpc@v1.47.0: read "https:/proxy.golang.org/@v/v1.47.0.zip": local error: tls: bad record MAC
#0 11.41 pkg/adaptor/proxy/proxy.go:21:2: google.golang.org/grpc@v1.47.0: read "https:/proxy.golang.org/@v/v1.47.0.zip": local error: tls: bad record MAC
#0 11.41 pkg/adaptor/hypervisor/ibmcloud/podvminfo.go:11:2: google.golang.org/grpc@v1.47.0: read "https:/proxy.golang.org/@v/v1.47.0.zip": local error: tls: bad record MAC
#0 11.41 pkg/adaptor/proxy/proxy.go:22:2: zip: checksum error
#0 11.74 go: downloading golang.org/x/sys v0.0.0-20220722155257-8c9f86f7a55f
#0 11.77 go: downloading github.com/IBM/go-sdk-core/v5 v5.6.3
#0 12.11 go: downloading github.com/IBM/vpc-go-sdk v1.0.1
#0 12.15 go: downloading github.com/containerd/containerd v1.6.6
#0 12.16 -> unzip /go/pkg/mod/cache/download/github.com/containerd/ttrpc/@v/v1.1.0.zip: zip: checksum error
#0 12.16 go: downloading github.com/kata-containers/kata-containers/src/runtime v0.0.0-20220913141151-9b49a6ddc6fd
#0 12.27 go: downloading google.golang.org/grpc v1.47.0
#0 12.35 go: downloading github.com/vmware/govmomi v0.29.0
#0 12.47 go: downloading github.com/vishvananda/netlink v1.1.1-0.20220115184804-dd687eb2f2d4
#0 12.51 -> unzip /go/pkg/mod/cache/download/github.com/avast/retry-go/v4/@v/v4.3.2.zip: zip: checksum error
#0 12.51 go: downloading github.com/containers/podman/v4 v4.2.0
#0 12.59 go: downloading github.com/gogo/protobuf v1.3.2
#0 12.66 go: downloading k8s.io/cri-api v0.23.1
#0 12.66 go: downloading github.com/opencontainers/runtime-spec v1.0.3-0.20211214071223-8958f93039ab
#0 12.75 go: downloading github.com/containernetworking/plugins v1.1.1
#0 13.80 pkg/adaptor/hypervisor/ibmcloud/vpcv1.go:8:2: zip: checksum error
#0 13.81 pkg/adaptor/hypervisor/ibmcloud/service.go:20:2: github.com/IBM/vpc-go-sdk@v1.0.1: Get "https://proxy.golang.org/github.com/%21i%21b%21m/vpc-go-sdk/@v/v1.0.1.zip": local error: tls: bad record MAC
#0 13.81 pkg/adaptor/proxy/service.go:12:2: unzip /go/pkg/mod/cache/download/github.com/avast/retry-go/v4/@v/v4.3.2.zip: zip: checksum error
#0 13.81 pkg/adaptor/proxy/service.go:14:2: github.com/containerd/containerd@v1.6.6: read "https:/proxy.golang.org/@v/v1.6.6.zip": local error: tls: bad record MAC
#0 13.81 pkg/util/agentproto/redirector.go:13:2: unzip /go/pkg/mod/cache/download/github.com/containerd/ttrpc/@v/v1.1.0.zip: zip: checksum error
#0 13.81 pkg/util/netops/netops.go:20:2: zip: checksum error
#0 13.81 pkg/adaptor/proxy/service.go:15:2: github.com/containers/podman/v4@v4.2.0: read "https:/proxy.golang.org/@v/v4.2.0.zip": local error: tls: bad record MAC
#0 13.81 proto/podvminfo/podvminfo.pb.go:10:2: github.com/gogo/protobuf@v1.3.2: Get "https://proxy.golang.org/github.com/gogo/protobuf/@v/v1.3.2.zip": local error: tls: bad record MAC
#0 13.81 pkg/util/agentproto/redirector.go:14:2: github.com/gogo/protobuf@v1.3.2: Get "https://proxy.golang.org/github.com/gogo/protobuf/@v/v1.3.2.zip": local error: tls: bad record MAC
#0 13.81 pkg/adaptor/hypervisor/ibmcloud/server.go:19:2: github.com/kata-containers/kata-containers/src/runtime@v0.0.0-20220913141151-9b49a6ddc6fd: read "https:/proxy.golang.org/@v/v0.0.0-20220913141151-9b49a6ddc6fd.zip": local error: tls: bad record MAC
#0 13.81 pkg/util/agentproto/redirector.go:15:2: github.com/kata-containers/kata-containers/src/runtime@v0.0.0-20220913141151-9b49a6ddc6fd: read "https:/proxy.golang.org/@v/v0.0.0-20220913141151-9b49a6ddc6fd.zip": local error: tls: bad record MAC
...
```

**Comment by liudalibj** [comment]
And the Dockerfile that I used.
```
FROM golang:1.19.3 AS m-builder
ARG CLOUD_PROVIDER
ENV CLOUD_PROVIDER=${CLOUD_PROVIDER}
COPY . cloud-api-adaptor
RUN git clone -b CCv0 https://github.com/kata-containers/kata-containers
WORKDIR cloud-api-adaptor
RUN if [ "$CLOUD_PROVIDER" = "libvirt" ] ; then apt-get update -y && apt-get install -y libvirt-dev; fi
RUN make cloud-api-adaptor

FROM fedora:36

ARG CLOUD_PROVIDER
ENV CLOUD_PROVIDER=${CLOUD_PROVIDER}
RUN if [ "$CLOUD_PROVIDER" = "libvirt" ] ; then dnf install -y libvirt-libs genisoimage /usr/bin/ssh && dnf clean all; fi
COPY --from=m-builder /go/cloud-api-adaptor/cloud-api-adaptor /usr/local/bin/cloud-api-adaptor-$CLOUD_PROVIDER
COPY --from=m-builder /go/cloud-api-adaptor/entrypoint.sh /usr/local/bin/entrypoint.sh
CMD ["entrypoint.sh"]
```
@jtumber-ibm Thanks for the help.

**Comment by jtumber-ibm** [comment]
I've got it working with the builder approach - I can do updates to this PR or open as a new PR. What would you prefer?

**Comment by liudalibj** [comment]
> I've got it working with the builder approach - I can do updates to this PR or open as a new PR. What would you prefer?

If the change is not big then you can do updates to this one in my branch, you should got the access.
If there are many new changes, you can close this PR and open a new PR in your branch.
Which way is fine to me. ^_^

**Comment by jtumber-ibm** [comment]
> > I've got it working with the builder approach - I can do updates to this PR or open as a new PR. What would you prefer?
> 
> If the change is not big then you can do updates to this one in my branch, you should got the access. If there are many new changes, you can close this PR and open a new PR in your branch. Which way is fine to me. ^_^

Created https://github.com/confidential-containers/cloud-api-adaptor/pull/540 which in the end requires less code changes - let me know your thoughts

**Comment by liudalibj** [comment]
Close this PR as https://github.com/confidential-containers/cloud-api-adaptor/pull/540 work fine in a better way.

**Pull request closed without merging**
