### PR TITLE
Fix workflow podvm builds

### PR DESCRIPTION
**Pull request by jtumber-ibm**
I've run tests for creating the builders using act.

Still running through the rest but it is a slow process. 

- Using the make targets for the steps, so that is grabs the versions 
- Added back in the cloud-provider specific image builds for the vsphere build
- Minor clean up of the workflow

### CODE REVIEW

**Comment by katexochen** [comment]
can we trigger a test run for this change?

**Comment by jtumber-ibm** [comment]
> can we trigger these workflows to test the change?

created release https://github.com/jtumber-ibm/cloud-api-adaptor/tree/v0.8.0-alpha.3 on my fork to run the builds, 

podvm_builder action: https://github.com/jtumber-ibm/cloud-api-adaptor/actions/runs/6733038159
podvm_binaries action: https://github.com/jtumber-ibm/cloud-api-adaptor/actions/runs/6733145029

**Review by katexochen — APPROVED** [review]
CI passed on your fork, changes look good, thanks! :)

**Comment by jtumber-ibm** [comment]
> ~CI passed on your fork, changes look good, thanks! :)~

Image build step failed, the centos failure was due to some missing changes from the remote->local updates. Which I have included in this PR. The other failures were due to authentication errors against dockerhub. Not 100% why as it was autenticated for the other images

**Review by stevenhorsman — APPROVED** [review]
Thanks for this update JT - I was just coming to think about doing this ready for the 0.8 RC, so I'm really please to see you do it :)

**Comment by jtumber-ibm** [comment]
> Do we need to add `hold` on this PR until we've resolved the centos issues to ensure we don't break anything (though it might already be broken)?

depends if centos is a blocker for the release.

@katexochen you can see the image build here with the latest updates https://github.com/jtumber-ibm/cloud-api-adaptor/actions/runs/6734612356 (+some required changes just to get it running from my fork)

**Comment by stevenhorsman** [comment]
> depends if centos is a blocker for the release.

Good point. I think the RH team are staying on 0.7 for the moment. @bpradipt should the centos build block us for 0.8, and the answer yes is fine!

**Review by katexochen — APPROVED** [review]

**Comment by bpradipt** [comment]
> > depends if centos is a blocker for the release.
> 
> Good point. I think the RH team are staying on 0.7 for the moment. @bpradipt should the centos build block us for 0.8, and the answer yes is fine!

We have tested the latest build with RHEL9 successfully. Didn't get time to test with CentOS, but it's not a blocker. Please proceed with the release.
Also can you please point me to the CentOS failure. I couldn't find it :-(

**Comment by katexochen** [comment]
> Also can you please point me to the CentOS failure. I couldn't find it :-(

It's on JT's fork: https://github.com/jtumber-ibm/cloud-api-adaptor/actions/runs/6734612356/job/18305896782

**Pull request merged**
