### PR TITLE
podvm: bump rust version to 1.66.0

### PR DESCRIPTION
**Pull request by snir911**
as it's required by kata-containers

Fixes: #481
Signed-off-by: Snir Sheriber <ssheribe@redhat.com>

later we can try and fetch the version from kata-containers versions file

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks @snir911 - I added this to my todo list to check this morning after I saw Pradipta's post, so nice to see you've taken care of it!

**Review by littlejawa — APPROVED** [review]
LGTM
Thanks @snir911 !

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @snir911

**Comment by stevenhorsman** [comment]
@snir911 - Sorry, a bit late here, but does the rhel podvm_builder need it's rust version bumped too?

**Comment by snir911** [comment]
ouch, nice catch @stevenhorsman i thought i did but apparently i changed it in the wrong file on the other PR :P I'll fix it

**Pull request merged**
