### PR TITLE
controller: mv peer-pod-controller peerpodconfig-ctrl 

### PR DESCRIPTION
**Pull request by snir911**
to match the controller name

Fixes: #707
Signed-off-by: Snir Sheriber <ssheribe@redhat.com>

### CODE REVIEW

**Comment by bpradipt** [comment]
@snir911 let's change the directory to `peerpodconfig-controller` to align with the CR name - `peerpodconfig`  :-)

**Comment by bpradipt** [comment]
> peer-pod-config-controller makes some of the object definitions names too long

I see. In that case `peerpodconfig-ctrl` (peerpodconfig being single word) ?

**Comment by snir911** [comment]
changed to peerpodconfig-ctrl

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @snir911

**Review by yoheiueda — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
