### PR TITLE
ibmcloud: Bug fix for test case with user image

### PR DESCRIPTION
**Pull request by sudharshanibm3**
Fixes the bug which Fails the pod with COMPLETED status

Fixes: #1001

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM

**Comment by sudharshanibm3** [comment]
Test Logs Before Bug Fix:
```
=== RUN   TestCreatePeerPodAndCheckUserLogs
=== RUN   TestCreatePeerPodAndCheckUserLogs/UserPeerPod_test
=== RUN   TestCreatePeerPodAndCheckUserLogs/UserPeerPod_test/Peer_pod_with_user_has_been_created
    common_suite_test.go:168: Log output of peer pod:otheruser
time="2023-06-15T18:51:30+05:30" level=info msg="PodVM name: user-pod"
time="2023-06-15T18:51:33+05:30" level=debug msg="Instance number: 0, Instance id: 07a7_46a7ee54-1854-4815-a85e-7d8797810319, Instance name: master-s390x-20-04-uptycs-1686821104-vsi"
time="2023-06-15T18:51:33+05:30" level=debug msg="Instance number: 1, Instance id: 0797_fea9eafc-28bf-4cfb-8d65-c15f68c4da20, Instance name: cdlleili-storage-test-1"
time="2023-06-15T18:51:33+05:30" level=debug msg="Instance number: 2, Instance id: 0797_e69eda46-b931-440d-a552-944de231a9a1, Instance name: cdlleili-storage-test-0"
time="2023-06-15T18:51:33+05:30" level=debug msg="Instance number: 3, Instance id: 0787_929cb956-6d6f-453c-9993-4a21491550a8, Instance name: podvm-swathi-peer-pod-new-86ff1b8c"
time="2023-06-15T18:51:33+05:30" level=debug msg="Instance number: 4, Instance id: 0787_2ea4acad-e087-4392-9193-5cc830df5378, Instance name: podvm-shan-auth-peer-pod-b8e5e7d9"
time="2023-06-15T18:51:33+05:30" level=debug msg="Instance number: 5, Instance id: 0787_fa548f77-a47c-4ebf-8218-db7b2eedc8a7, Instance name: podvm-sudharshan-peer-pod-d3d2ba7e"
time="2023-06-15T18:51:33+05:30" level=debug msg="Instance number: 6, Instance id: 0787_6654125e-9657-4ee4-8001-17ce1c682ecc, Instance name: podvm-sysdig-peer-pod-137f865f"
time="2023-06-15T18:51:33+05:30" level=debug msg="Instance number: 7, Instance id: 0787_1a025cb2-ce1d-4e61-9582-44b48b35dc43, Instance name: podvm-authenticatedimage-pod-dab7f86c"
time="2023-06-15T18:51:33+05:30" level=debug msg="Instance number: 8, Instance id: 0797_39dbbbe6-c360-4233-9e7f-087eea06f270, Instance name: podvm-nginx-b78b702c"
time="2023-06-15T18:51:33+05:30" level=debug msg="Instance number: 9, Instance id: 0787_cca64abc-0957-4512-b2ca-2ccd6ff9194f, Instance name: podvm-large-new-81-pod-ce075fa0"
time="2023-06-15T18:51:33+05:30" level=debug msg="Instance number: 10, Instance id: 0787_377ce92a-d744-4445-8884-f9b9d7251876, Instance name: podvm-swathi-peer-pod-new-86a61511"
time="2023-06-15T18:51:33+05:30" level=debug msg="Instance number: 11, Instance id: 0787_5b1f5139-a972-453a-a021-728506333689, Instance name: perf-test-xixuejia-xvsi"
    ibmcloud_test.go:126: PodVM was not created
time="2023-06-15T18:51:33+05:30" level=info msg="Deleting pod... user-pod"
--- FAIL: TestCreatePeerPodAndCheckUserLogs (35.13s)
    --- FAIL: TestCreatePeerPodAndCheckUserLogs/UserPeerPod_test (35.12s)
        --- FAIL: TestCreatePeerPodAndCheckUserLogs/UserPeerPod_test/Peer_pod_with_user_has_been_created (4.57s)
FAIL
FAIL    github.com/confidential-containers/cloud-api-adaptor/test/e2e   88.357s
FAIL
```


Test Log After Bug Fix:
```
=== RUN   TestCreatePeerPodAndCheckUserLogs
=== RUN   TestCreatePeerPodAndCheckUserLogs/UserPeerPod_test
=== RUN   TestCreatePeerPodAndCheckUserLogs/UserPeerPod_test/Peer_pod_with_user_has_been_created
    common_suite_test.go:168: Log output of peer pod:otheruser
time="2023-06-15T19:05:41+05:30" level=info msg="Deleting pod... user-pod"
--- PASS: TestCreatePeerPodAndCheckUserLogs (31.23s)
    --- PASS: TestCreatePeerPodAndCheckUserLogs/UserPeerPod_test (31.23s)
        --- PASS: TestCreatePeerPodAndCheckUserLogs/UserPeerPod_test/Peer_pod_with_user_has_been_created (0.65s)
PASS
ok      github.com/confidential-containers/cloud-api-adaptor/test/e2e   81.863s
```

**Review by jtumber-ibm — DISMISSED** [review]

**Comment by jtumber-ibm** [comment]
@sudharshanibm3 is the testCommands optional for a test?

**Comment by sudharshanibm3** [comment]
@sudharshanibm3 is the testCommands optional for a test?

Hi @jtumber-ibm ,
Not all the test cases uses testCommands,
yes it's a optional method that can be attached with test case

**Comment by jtumber-ibm** [comment]
> @sudharshanibm3 is the testCommands optional for a test?
> 
> Hi @jtumber-ibm , Not all the test cases uses testCommands, yes it's a optional method that can be attached with test case

Then should it not be

```go
if tc.podState == v1.PodRunning {
   if len(tc.testCommands) > 0 {
      ....
   }
   tc.assert.HasPodVM(t, tc.pod.Name)
}
``` 

?

**Review by jtumber-ibm — APPROVED** [review]

**Pull request merged**
