### PR TITLE
vsphere: Add additional startup option checking

### PR DESCRIPTION
**Pull request by caavery**
Fixes: #635

This patch also updates kustomization.yaml with the new options and provides better descriptions.

### CODE REVIEW

**Comment by snir911** [comment]
needs rebase due to the TLS PR merge

**Comment by caavery** [comment]
Yeap I saw that

**Comment by caavery** [comment]
@snir911 
I resolved the conflicts on this website and it lopped my commit message off. How  do I fix this?
Thanks

**Comment by caavery** [comment]
Never mind I'm going to close this pull and open a new one

**Pull request closed without merging**
