### PR TITLE
peerpodconfig-ctrl: Fix the gh-action job

### PR DESCRIPTION
**Pull request by bpradipt**
The gh-action job included incorrect build target resulting in job failure.

Fixes: #1525

### CODE REVIEW

**Comment by bpradipt** [comment]
@snir911 @huoqifeng this bug got introduced by my earlier PR to enable gh-action job for building peerpodconfig-ctrl.
This fixes the bug.
I have also opened a separate issue to work on the multi-arch enablement for the image. But I'll wait for the consensus on how to build the multi-arch image that is currently being looked by @huoqifeng

**Review by snir911 — APPROVED** [review]

**Review by huoqifeng — APPROVED** [review]
LGTM

**Comment by huoqifeng** [comment]
I think it's good to fix the build error temporary and make muti-arch images aligned with CAA. @bpradipt I'm guessing we'll need the peerpod-ctl and peerpodconfig-ctl included in image built from operator after https://github.com/confidential-containers/operator/pull/249 merged eventually, right?

**Comment by bpradipt** [comment]
> I think it's good to fix the build error temporary and make muti-arch images aligned with CAA. @bpradipt I'm guessing we'll need the peerpod-ctl and peerpodconfig-ctl included in image built from operator after [confidential-containers/operator#249](https://github.com/confidential-containers/operator/pull/249) merged eventually, right?

Right

**Pull request merged**
