### PR TITLE
Post v0.7.0 release updates

### PR DESCRIPTION
**Pull request by wainersm**
As delineated in our [release process post-release phase](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/docs/Release-Process.md#post-release) we should revert some changes after the release to get latest updates of components. Actually this PR contain two reverts that aren't described on current release document, but are on the new version on PR #1254 (Release process document improvements).

Ran the libvirt e2e tests successfully: 

```
Wait for the cc-operator-daemon-install DaemonSet be available
Wait for the pod cc-operator-daemon-install-xr8kf be ready
Wait for the cloud-api-adaptor-daemonset DaemonSet be available
Wait for the pod cloud-api-adaptor-daemonset-f9bwl be ready
Wait for the kata-remote runtimeclass be created
=== RUN   TestLibvirtCreateSimplePod
=== RUN   TestLibvirtCreateSimplePod/SimplePeerPod_test
=== RUN   TestLibvirtCreateSimplePod/SimplePeerPod_test/PodVM_is_created
time="2023-07-27T15:58:23-03:00" level=info msg="Deleting pod... nginx"
--- PASS: TestLibvirtCreateSimplePod (85.07s)
    --- PASS: TestLibvirtCreateSimplePod/SimplePeerPod_test (85.07s)
        --- PASS: TestLibvirtCreateSimplePod/SimplePeerPod_test/PodVM_is_created (0.04s)
=== RUN   TestLibvirtCreatePodWithConfigMap
=== RUN   TestLibvirtCreatePodWithConfigMap/ConfigMapPeerPod_test
=== RUN   TestLibvirtCreatePodWithConfigMap/ConfigMapPeerPod_test/Configmap_is_created_and_contains_data
time="2023-07-27T15:59:33-03:00" level=info msg="Data Inside Configmap: Hello, world"
time="2023-07-27T15:59:33-03:00" level=info msg="Deleting Configmap... nginx-config"
time="2023-07-27T15:59:33-03:00" level=info msg="Deleting pod... nginx-configmap-pod"
--- PASS: TestLibvirtCreatePodWithConfigMap (70.11s)
    --- PASS: TestLibvirtCreatePodWithConfigMap/ConfigMapPeerPod_test (70.11s)
        --- PASS: TestLibvirtCreatePodWithConfigMap/ConfigMapPeerPod_test/Configmap_is_created_and_contains_data (5.07s)
=== RUN   TestLibvirtCreatePodWithSecret
=== RUN   TestLibvirtCreatePodWithSecret/SecretPeerPod_test
=== RUN   TestLibvirtCreatePodWithSecret/SecretPeerPod_test/Secret_has_been_created_and_contains_data
time="2023-07-27T16:00:58-03:00" level=info msg="Username from secret inside pod: admin"
time="2023-07-27T16:01:03-03:00" level=info msg="Password from secret inside pod: password"
time="2023-07-27T16:01:03-03:00" level=info msg="Deleting Secret... nginx-secret"
time="2023-07-27T16:01:03-03:00" level=info msg="Deleting pod... nginx-secret-pod"
--- PASS: TestLibvirtCreatePodWithSecret (90.14s)
    --- PASS: TestLibvirtCreatePodWithSecret/SecretPeerPod_test (90.14s)
        --- PASS: TestLibvirtCreatePodWithSecret/SecretPeerPod_test/Secret_has_been_created_and_contains_data (10.10s)
PASS
ok      github.com/confidential-containers/cloud-api-adaptor/test/e2e   1554.011s
```

### CODE REVIEW

**Review by jtumber-ibm — APPROVED** [review]
lgtm

**Review by katexochen — APPROVED** [review]

**Comment by bpradipt** [comment]
@wainersm what about switching to main/latest in the Dockerfiles and the github actions ?

**Comment by wainersm** [comment]
> @wainersm what about switching to main/latest in the Dockerfiles and the github actions ?

Good catch @bpradipt, I will be reverting that as well.

Your comment, @bpradipt , made me realize another flaw on on our release process... the `podvm/Dockerfile.*` files are kept `CAA_SRC_REF="main"`. That variable is overridden in `.github/workflows/podvm_builder.yaml` but we also keep it pointing to `main`. However I don't think it harmed the 0.7.0 release because luckily I pinned the CAA image on the overlay files, and we never tagged the podvm images (see https://github.com/confidential-containers/cloud-api-adaptor/issues/1109). Of course, if one wants to rebuild peer-pods completely from the v0.7.0 tag, podvm will be referencing to wrong sources :(

As for the attestation agent, keep it pinned to guest-component's v0.7.0 tag until someone needs to pick up a newer version?    

@stevenhorsman FYI

**Comment by wainersm** [comment]
ok, I think it can be merged. One last review @jtumber-ibm @katexochen @bpradipt ?

**Review by surajssd — APPROVED** [review]

**Comment by bpradipt** [comment]
Merging this with silent prayers

**Pull request merged**
