### PR TITLE
all: remove secrets from entrypoint.sh

### PR DESCRIPTION
**Pull request by jtumber-ibm**
These secrets can be passed in as environment variables.

Fixes: #313

Signed-off-by: James Tumber <james.tumber@ibm.com>

### CODE REVIEW

**Review by snir911 — APPROVED** [review]
LGTM, thanks! one question, do we get any useful error if one of these fields is missing? if not i'd consider using the `test_vars` in entrypoint.sh for these variables until we'll have a proper checking&erroring for this in the caa binary.

**Comment by jtumber-ibm** [comment]
> LGTM, thanks! one question, do we get any useful error if one of these fields is missing? if not i'd consider using the `test_vars` in entrypoint.sh for these variables until we'll have a proper checking&erroring for this in the caa binary.

Good point, I've added in the test for each provider. Pretty sure that there wouldn't be an error message until it tried to authenticate.

**Review by snir911 — APPROVED** [review]
Thanks! LGTM, if tested (i didn't test, I'm assuming vars should be available for the executed caa binary )

**Comment by jtumber-ibm** [comment]
> Thanks! LGTM, if tested (i didn't test, I'm assuming vars should be available for the executed caa binary )

Yes they are, tested for ibmcloud.

**Review by knrt10 — APPROVED** [review]

**Pull request merged**
