### PR TITLE
github: add citation

### PR DESCRIPTION
**Pull request by katexochen**
Add a citation so people can easily cite our software and use a
unified format.

[See the documentation for details](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)

### CODE REVIEW

**Comment by fitzthum** [comment]
This is cool. Will we need to continuously update that version number? We should think about adding to other repos as well.

**Comment by katexochen** [comment]
> This is cool. Will we need to continuously update that version number? We should think about adding to other repos as well.

I'll write a bot as soon as I find the time. And yes, I'll open PRs at the other repos, too. :)

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @katexochen

**Review by stevenhorsman — APPROVED** [review]
LGTM. One point is that we might want to add bumping the version of this at least at a release boundary to the release process docs until this is automated?

**Comment by katexochen** [comment]
@stevenhorsman Added a line to release process documentation.

**Review by surajssd — APPROVED** [review]

**Pull request merged**
