### PR TITLE
probe: make startup probe optional

### PR DESCRIPTION
**Pull request by huoqifeng**
Fixes: #1513

### CODE REVIEW

**Comment by huoqifeng** [comment]
Run service as by add `-startup-probe false`:
```
exec ./cloud-api-adaptor ibmcloud \
   -iam-service-url "${IBMCLOUD_IAM_ENDPOINT}" \
   -vpc-service-url "${IBMCLOUD_VPC_ENDPOINT}" \
   -resource-group-id "${IBMCLOUD_RESOURCE_GROUP_ID}" \
   -key-id "${IBMCLOUD_SSH_KEY_ID}" \
   -image-id "${IBMCLOUD_PODVM_IMAGE_ID}" \
   -profile-name "${IBMCLOUD_PODVM_INSTANCE_PROFILE_NAME}" \
   -profile-list "${IBMCLOUD_PODVM_INSTANCE_PROFILE_LIST}" \
   -zone-name "${IBMCLOUD_ZONE}" \
   -primary-subnet-id "${IBMCLOUD_VPC_SUBNET_ID}" \
   -primary-security-group-id "${IBMCLOUD_VPC_SG_ID}" \
   -vpc-id "${IBMCLOUD_VPC_ID}" \
   -pods-dir /run/peerpod/pods \
   -cri-runtime-endpoint /var/run/containerd/containerd.sock \
   -socket /run/peerpod/hypervisor.sock \
   -startup-probe false\
   > /var/log/cloud-api-adaptor.log 2>&1 &
```

**Review by liudalibj — APPROVED** [review]
LGTM

**Comment by liudalibj** [comment]
> Run service similar as by add `-startup-probe false`:
> 
> ```
> exec ./cloud-api-adaptor ibmcloud \
>    -iam-service-url "${IBMCLOUD_IAM_ENDPOINT}" \
>    -vpc-service-url "${IBMCLOUD_VPC_ENDPOINT}" \
>    -resource-group-id "${IBMCLOUD_RESOURCE_GROUP_ID}" \
>    -key-id "${IBMCLOUD_SSH_KEY_ID}" \
>    -image-id "${IBMCLOUD_PODVM_IMAGE_ID}" \
>    -profile-name "${IBMCLOUD_PODVM_INSTANCE_PROFILE_NAME}" \
>    -profile-list "${IBMCLOUD_PODVM_INSTANCE_PROFILE_LIST}" \
>    -zone-name "${IBMCLOUD_ZONE}" \
>    -primary-subnet-id "${IBMCLOUD_VPC_SUBNET_ID}" \
>    -primary-security-group-id "${IBMCLOUD_VPC_SG_ID}" \
>    -vpc-id "${IBMCLOUD_VPC_ID}" \
>    -pods-dir /run/peerpod/pods \
>    -cri-runtime-endpoint /var/run/containerd/containerd.sock \
>    -socket /run/peerpod/hypervisor.sock \
>    -startup-probe false\
>    > /var/log/cloud-api-adaptor.log 2>&1 &
> ```

should we add this to one document place?

**Comment by huoqifeng** [comment]
Reported https://pkg.go.dev/vuln/GO-2023-2102 in the vulscan.

**Review by yoheiueda — COMMENTED** [review]
Thank you very much for this patch. I just encounter this problem too.

Adding an option for this feature is a good idea, but I also come up with another solution.

The PeerPodService in `cloud-api-adaptor` has a similar problem, but it just print warning messages instead of existing when `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` are not defined.

https://github.com/confidential-containers/cloud-api-adaptor/blob/90ccfc3fa0ee56c2fc61b23ecf3731f819faf875/pkg/adaptor/cloud/cloud.go#L87-L90

I think that it is comprehensive if both the probe and the PeerPodService have consistent behaviors.

**Comment by huoqifeng** [comment]
Thanks @yoheiueda , I agree it's more simpler, made the change.

**Review by yoheiueda — APPROVED** [review]
LGTM. Thank you very much!

**Pull request merged**
