### PR TITLE
e2e: remove build tags in provision_*.go files

### LINKED ISSUE #658: e2e test: compile error if only the tag "ibmcloud" is specified
When attempting to run e2e tests for the ibmcloud provider only, I set tag as ibmcloud only:
```
CLOUD_PROVIDER=ibmcloud GOFLAGS="-tags=ibmcloud" make test-e2e
```

However, I got following compile error:
```
test/e2e/provision.go:80:22: undefined: NewAzureCloudProvisioner
test/e2e/provision.go:82:22: undefined: NewLibvirtProvisioner
note: module requires Go 1.18
FAIL	github.com/confidential-containers/cloud-api-adaptor/test/e2e [build failed]
FAIL
```

### PR DESCRIPTION
**Pull request by genjuro214**
Avoid compile error when using tag to filter tests

Fixes #658

Signed-off-by: Lei Li <genjuro214@gmail.com>

### CODE REVIEW

**Comment by yoheiueda** [comment]
Could you add the following build constraint in `test/e2e/provision_libvirt.go`?  

```
//go:build cgo
```

The build tag `cgo` is automatically set only when CGO is enabled. This will be convenient for developers in environments where libvirt library is not available as discussed at https://github.com/confidential-containers/cloud-api-adaptor/pull/618#issuecomment-1437738050

We probably need a new file something like `test/e2e/provision_libvirt_nocgo.go` with the following content.

```
//go:build !cgo

package e2e

func NewLibvirtProvisioner(properties map[string]string) (CloudProvision, error) {
	panic("CGO is not enabled")
}
```

This file will suppress a build error at the `provision.go` when CGO is not enabled. 
https://github.com/confidential-containers/cloud-api-adaptor/blob/8573d8e55a5fd9e89ceb07fc4b5bddcd30659b2a/test/provisioner/provision.go#L82

**Comment by genjuro214** [comment]
@yoheiueda , I have made changes according to your comments above. However, when running e2e with CGO disabled, I encountered the following error:
```
# CGO_ENABLED=0 CLOUD_PROVIDER=ibmcloud make test-e2e
go test -v -tags=aws,azure,ibmcloud,vsphere,libvirt -timeout 20m -count=1 ./test/e2e
# github.com/confidential-containers/cloud-api-adaptor/test/e2e [github.com/confidential-containers/cloud-api-adaptor/test/e2e.test]
test/e2e/libvirt_test.go:23:15: undefined: libvirt.NewConnect
test/e2e/libvirt_test.go:28:38: undefined: libvirt.CONNECT_LIST_DOMAINS_ACTIVE
note: module requires Go 1.18
FAIL	github.com/confidential-containers/cloud-api-adaptor/test/e2e [build failed]
FAIL
```

Do we also need to update the build constraint in `test/e2e/libvirt_test.go`:
```
//go:build libvirt && cgo
```

So that the libvirt tests will not be run with CGO disabled? Is this expected?

**Comment by yoheiueda** [comment]
Oh, yes.

You need to add the same build constraint to `libvirt_test.go`.


```
//go:build cgo
```

If you remove `libvirt` tag from `provision_libvirt.go`, I don't think `libvirt` is necessary in `libvirt_test.go`

**Comment by genjuro214** [comment]
I think `libvirt` is necessary in `libvirt_test.go`, so that we can run libvirt tests only with CGO enabled?
```
CGO_ENABLED=1 GOFLAGS="-tags=libvirt" CLOUD_PROVIDER=libvirt make test-e2e
```

**Comment by huoqifeng** [comment]
@genjuro214 I'm not sure whether we want to remove the build flag because usually the test will be run against a single provider. Maybe an alternative approach is like this https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/cmd/cloud-api-adaptor/cloudmgr/manager.go#L19

**Comment by huoqifeng** [comment]
If the purpose of GetCloudProvisioner factory is intend to remove the build flag, it's OK for me :-) @wainersm

**Comment by yoheiueda** [comment]
> I think `libvirt` is necessary in `libvirt_test.go`, so that we can run libvirt tests only with CGO enabled?
> 
> ```
> CGO_ENABLED=1 GOFLAGS="-tags=libvirt" CLOUD_PROVIDER=libvirt make test-e2e
> ```

Ah, yes. That is correct. Please keep the `libvirt` tag in the file.

BTW, built-in cloud providers are now specified by `BUILTIN_CLOUD_PROVIDERS`. `CLOUD_PROVIDER` does not control the `-tags` option, although directly specifying `GOFLAGS` still works.

https://github.com/confidential-containers/cloud-api-adaptor/pull/654

**Comment by yoheiueda** [comment]
> @genjuro214 I'm not sure whether we want to remove the build flag because usually the test will be run against a single provider.

The current code structure causes a build error when a single cloud provider tag is specified, so I think this PR is valid as a fix for the problem.

>  Maybe an alternative approach is like this https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/cmd/cloud-api-adaptor/cloudmgr/manager.go#L19

I also agree that we should refactor the related code in a similar way, so that a single or subset of cloud providers can be enabled. I think it is OK to refactor the code after this PR is merged.

**Review by yoheiueda — APPROVED** [review]
LGTM

**Review by huoqifeng — APPROVED** [review]
/lgtm, I'm OK for the fix and let's refactor in later PR, thanks @genjuro214

**Comment by genjuro214** [comment]
Can't rebase and merge due to conflicts. I tried to create a new PR: https://github.com/confidential-containers/cloud-api-adaptor/pull/669
and close this one.

**Pull request closed without merging**
