### PR TITLE
versions: Point to 0.5 releases

### PR DESCRIPTION
**Pull request by stevenhorsman**
- Update attestation-agent and kata-containers to the 0.5 tags

Fixes: #814

### CODE REVIEW

**Comment by stevenhorsman** [comment]
Now the kata-containers tag for 0.5 has been cut - update to use this version. I think I've got the places we pull it in, but @bpradipt and co - please double check I've not missed some.

**Comment by stevenhorsman** [comment]
I built a podvm image from this and ran the e2e tests and they passed:
```
Wait for the pod cc-operator-daemon-install-9wq25 be ready
Wait for the kata runtimeclass be created
=== RUN   TestCreateSimplePod
=== RUN   TestCreateSimplePod/Simple_Peer_Pod
=== RUN   TestCreateSimplePod/Simple_Peer_Pod/PodVM_is_created
time="2023-04-14T09:49:47-07:00" level=info msg="PodVM name: simple-peer-pod"
time="2023-04-14T09:49:48-07:00" level=debug msg="Instance number: 0, Instance id: 02f7_448c8563-06ff-4a47-9d90-922754523e0a, Instance name: podvm-simple-peer-pod-49d67bcc"
--- PASS: TestCreateSimplePod (57.54s)
    --- PASS: TestCreateSimplePod/Simple_Peer_Pod (57.54s)
        --- PASS: TestCreateSimplePod/Simple_Peer_Pod/PodVM_is_created (1.72s)

```

**Review by yoheiueda — COMMENTED** [review]
Do we need to update the reference in `go.mod? I think it is OK to update in another PR.

https://github.com/confidential-containers/cloud-api-adaptor/blob/f91dd09c08c47608cbf168faca2c51e056b0888b/go.mod#L48

We can update it like this.
```
go get github.com/kata-containers/kata-containers@CC-0.5.0
```

We also have indirect references in the following `go.mod` files.

* `peerpod-ctrl/go.mod`
* `csi-wrapper/go.mod`

These `go.mod` files also contain referenes back to `github.com/confidential-containers/cloud-api-adaptor`, but we cannot update them within a single PR.

**Comment by bpradipt** [comment]
> Do we need to update the reference in `go.mod? I think it is OK to update in another PR.
> 
> https://github.com/confidential-containers/cloud-api-adaptor/blob/f91dd09c08c47608cbf168faca2c51e056b0888b/go.mod#L48
> 
> We can update it like this.
> 
> ```
> go get github.com/kata-containers/kata-containers@CC-0.5.0

I think we should update the kata-containers module in this PR. This will ensure all key changes are in one place

> ```
> 
> We also have indirect references in the following `go.mod` files.
> 
> * `peerpod-ctrl/go.mod`
> * `csi-wrapper/go.mod`
> 
> These `go.mod` files also contain referenes back to `github.com/confidential-containers/cloud-api-adaptor`, but we cannot update them within a single PR.

We can update these in a follow-on PR.

**Comment by stevenhorsman** [comment]
Thanks for the reminder!. I've pushed the result of 
`go get github.com/kata-containers/kata-containers@CC-0.5.0` to this PR

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @stevenhorsman

**Review by yoheiueda — APPROVED** [review]
LGTM. @stevenhorsman thank you very much!

> We can update these in a follow-on PR.

@bpradipt OK. It makes sense. I'll prepare follow-on PR, since I am already working on updating `go.mod` files in https://github.com/confidential-containers/cloud-api-adaptor/issues/475

**Review by jensfr — APPROVED** [review]
Lgtm

**Comment by stevenhorsman** [comment]
> LGTM. @stevenhorsman thank you very much!
> 
> > We can update these in a follow-on PR.
> 
> @bpradipt OK. It makes sense. I'll prepare follow-on PR, since I am already working on updating `go.mod` files in #475

Just to check - do we need this follow on PR before we cut the release?

**Comment by yoheiueda** [comment]
> Just to check - do we need this follow on PR before we cut the release?

@bpradipt do we need to update the submodules before or after the release? Do you think which is better?

I prepare an draft PR to include the references to v0.5.0-alpha. Please post your comments in #817. If we need to update the sub modules after the release, I'll update the PR.

**Pull request merged**
