### PR TITLE
entrypoint: exec cloud-api-adaptor process

### PR DESCRIPTION
**Pull request by snir911**
also use exec form in Dockerfile

Fixes: #289
Signed-off-by: Snir Sheriber <ssheribe@redhat.com>

### CODE REVIEW

**Comment by snir911** [comment]
@caavery could you please confirm it fixes the issue
images for testing:
quay.io/snir/cloud-api-adaptor-vsphere:sig_fix
quay.io/snir/cloud-api-adaptor-libvirt:sig_fix

**Comment by wainersm** [comment]
hi @snir911 ! This is going to ensure that SIGTERM is cascaded to the `cloud-api-adaptor-PROVIDER` process. Okay, my question is: is there anything else that we should be doing on `cloud-api-adaptor-PROVIDER` to kindly terminate the process? 

Other than that, your change looks good to me.

**Comment by snir911** [comment]
@wainersm I'm not sure i'm getting your point, AFAIU it seems it terminates kindly when it gets SIGTERM, so it should be enough

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @snir911

**Review by littlejawa — APPROVED** [review]

**Pull request merged**
