### PR TITLE
libvirt: Improve the setup instructions to run libvirt tests

### PR DESCRIPTION
**Pull request by ldoktor**
Few things that should simplify the setup for the newcomers

### CODE REVIEW

**Comment by liudalibj** [comment]
thanks @ldoktor these change are good to me, as we change the repo in a new files structure, would you like rebase this PR with main branch.
The files you want to update are at `https://github.com/confidential-containers/cloud-api-adaptor/tree/main/src/cloud-api-adaptor/libvirt`

**Comment by ldoktor** [comment]
Sure, changes:

* Rebased (clean apply except of the extra `[cloud-api-adaptor](../) folder` note that had been incorporated)
* New commit to unify execution from the `cloud-api-adaptor` folder

**Review by liudalibj — APPROVED** [review]
Thanks LGTM

**Review by wainersm — APPROVED** [review]
Hi @ldoktor , thanks for those updates!

And sorry for taking too long to ack...

**Pull request merged**
