### PR TITLE
Azure resource cleanup

### PR DESCRIPTION
**Pull request by jepio**
Cleanup NIC/disk together with VM using "DeleteOption" properties when creating the VM.

Haven't tested this yet!

### CODE REVIEW

**Review by surajssd — APPROVED** [review]

**Review by mkulke — CHANGES_REQUESTED** [review]
Sadly this will still leak nics for me:

## steps to reproduce:

Reference an image id that doesn't exist in peer pod config map:

## daemonset logs

```
2023/07/19 09:03:57 [adaptor] server started
2023/07/19 09:04:14 [podnetwork] routes on netns /var/run/netns/cni-20e9af7b-9e34-a182-7b93-82d3678334af
2023/07/19 09:04:14 [podnetwork]     default via 10.244.0.1 dev eth0
2023/07/19 09:04:14 [adaptor/cloud] stored /run/peerpod/pods/5afe4bf40f9c5818f019632d68b0077fa21c05533acd4ec1b16923cff58b6f4f/daemon.json
2023/07/19 09:04:14 [adaptor/cloud] create a sandbox 5afe4bf40f9c5818f019632d68b0077fa21c05533acd4ec1b16923cff58b6f4f for pod nginx-caa-5c4fc7b6c-8299r in namespace default (netns: /var/run/netns/cni-20e9af7b-9e34-a182-7b93-82d3678334af)
Using default instance type ("Standard_D8as_v5")
2023/07/19 09:04:17 [adaptor/cloud/azure] CreateInstance: name: "podvm-nginx-caa-5c4fc7b6c-8299r-5afe4bf4"
2023/07/19 09:04:19 [adaptor/cloud/azure] deleted disk successfully: podvm-nginx-caa-5c4fc7b6c-8299r-5afe4bf4-disk
2023/07/19 09:04:20 [adaptor/cloud/azure] deleting nic (podvm-nginx-caa-5c4fc7b6c-8299r-5afe4bf4-net): beginning network interface deletion: DELETE https://management.azure.com/subscriptions/REDACTED/resourceGroups/mgns/providers/Microsoft.Network/networkInterfaces/podvm-nginx-caa-5c4fc7b6c-8299r-5afe4bf4-net
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: NicReservedForAnotherVm
--------------------------------------------------------------------------------
{
  "error": {
    "code": "NicReservedForAnotherVm",
    "message": "Nic(s) in request is reserved for another Virtual Machine for 180 seconds. Please provide another nic(s) or retry after 180 seconds. Reserved VM: /subscriptions/REDACTED/resourceGroups/mgns/providers/Microsoft.Compute/virtualMachines/podvm-nginx-caa-5c4fc7b6c-8299r-5afe4bf4",
    "details": []
  }
}
--------------------------------------------------------------------------------
2023/07/19 09:04:20 [adaptor/cloud] creating an instance : Creating instance (<nil>): beginning VM creation or update: PUT https://management.azure.com/subscriptions/REDACTED/resourceGroups/mgns/providers/Microsoft.Compute/virtualMachines/podvm-nginx-caa-5c4fc7b6c-8299r-5afe4bf4
--------------------------------------------------------------------------------
RESPONSE 404: 404 Not Found
ERROR CODE: GalleryImageNotFound
--------------------------------------------------------------------------------
{
  "error": {
    "code": "GalleryImageNotFound",
    "message": "\"The gallery image /subscriptions/REDACTED/resourceGroups/mgns-eastus/providers/Microsoft.Compute/galleries/caasnp/images/peerpod/versions/0.0.2 is not available in eastus region. Please contact image owner to replicate to this region, or change your requested region.\"",
    "target": "imageReference"
  }
}
--------------------------------------------------------------------------------
2023/07/19 09:04:20 [adaptor/proxy] shutting down socket forwarder
2023/07/19 09:04:20 [adaptor/cloud/azure] finding VM name using regexp:[]
2023/07/19 09:04:20 [adaptor/cloud] Error deleting an instance : VM name not found
2023/07/19 09:04:20 [tunneler/vxlan] Delete tc redirect filters on eth0 and eth0 in the network namespace /var/run/netns/cni-20e9af7b-9e34-a182-7b93-82d3678334af
2023/07/19 09:04:20 [adaptor/cloud] tearing down netns /var/run/netns/cni-20e9af7b-9e34-a182-7b93-82d3678334af: failed to tear down tunnel "vxlan": failed to delete a tc redirect filter from vxlan1 to eth0: failed to get interface vxlan1: Link not found
```

**Comment by jepio** [comment]
I moved NIC deletion to a goroutine and delay 180s when retrying (seems it's really needed).

Here's the log from a failed VM creation (with k8s or caa retrying the vm creation in a loop):
```
2023/07/19 16:05:19 [adaptor/cloud/azure] CreateInstance: name: "podvm-nginx-6c48b665d4-tdrks-c0ef99ca"
2023/07/19 16:05:19 [adaptor/cloud/azure] deleted disk successfully: podvm-nginx-6c48b665d4-tdrks-c0ef99ca-disk
2023/07/19 16:05:19 [adaptor/cloud] creating an instance : Creating instance (<nil>): beginning VM creation or update: PUT https://management.azure.com/subscriptions/xxx/resourceGroups/jepio-caa-rg-node/providers/Microsoft.Compute/virtualMachines/podvm-nginx-6c48b665d4-tdrks-c0ef99ca
--------------------------------------------------------------------------------
RESPONSE 404: 404 Not Found
ERROR CODE: GalleryImageNotFound
--------------------------------------------------------------------------------
{
  "error": {
    "code": "GalleryImageNotFound",
    "message": "\"The gallery image /CommunityGalleries/cocopreview-91c44057-c3ab-4652-bf00-9242d5a90170/Images/ubuntu2204-caa-snp/Versions/0.6.2 is not available in eastus2 region. Please contact image owner to replicate to this region, or change your requested region.\"",
    "target": "imageReference"
  }
}
--------------------------------------------------------------------------------
2023/07/19 16:05:19 [adaptor/proxy] shutting down socket forwarder
2023/07/19 16:05:19 [adaptor/cloud/azure] finding VM name using regexp:[]
2023/07/19 16:05:19 [adaptor/cloud] Error deleting an instance : VM name not found
2023/07/19 16:05:19 [tunneler/vxlan] Delete tc redirect filters on eth0 and eth0 in the network namespace /var/run/netns/cni-33a3dda2-4831-22df-2d3f-1d95691ab241
2023/07/19 16:05:19 [adaptor/cloud] tearing down netns /var/run/netns/cni-33a3dda2-4831-22df-2d3f-1d95691ab241: failed to tear down tunnel "vxlan": failed to delete a tc redirect filter from vxlan1 to eth0: failed to get interface vxlan1: Link not found
2023/07/19 16:05:19 [adaptor/cloud/azure] successfully deleted nic (podvm-nginx-6c48b665d4-tdrks-3f876654-net) in background
2023/07/19 16:05:34 [adaptor/cloud/azure] successfully deleted nic (podvm-nginx-6c48b665d4-tdrks-ccdb9636-net) in background
2023/07/19 16:05:47 [adaptor/cloud/azure] successfully deleted nic (podvm-nginx-6c48b665d4-tdrks-aece722e-net) in background
2023/07/19 16:06:00 [adaptor/cloud/azure] successfully deleted nic (podvm-nginx-6c48b665d4-tdrks-913d8d32-net) in background
2023/07/19 16:06:14 [adaptor/cloud/azure] successfully deleted nic (podvm-nginx-6c48b665d4-tdrks-c40d0456-net) in background
2023/07/19 16:06:27 [adaptor/cloud/azure] successfully deleted nic (podvm-nginx-6c48b665d4-tdrks-d1fbf282-net) in background
2023/07/19 16:06:40 [adaptor/cloud/azure] successfully deleted nic (podvm-nginx-6c48b665d4-tdrks-94597640-net) in background
2023/07/19 16:06:54 [adaptor/cloud/azure] successfully deleted nic (podvm-nginx-6c48b665d4-tdrks-675f341a-net) in background
2023/07/19 16:07:10 [adaptor/cloud/azure] successfully deleted nic (podvm-nginx-6c48b665d4-tdrks-e6e222fc-net) in background
2023/07/19 16:07:24 [adaptor/cloud/azure] successfully deleted nic (podvm-nginx-6c48b665d4-tdrks-5c1d21ea-net) in background
2023/07/19 16:07:38 [adaptor/cloud/azure] successfully deleted nic (podvm-nginx-6c48b665d4-tdrks-c0c28259-net) in background
2023/07/19 16:07:52 [adaptor/cloud/azure] successfully deleted nic (podvm-nginx-6c48b665d4-tdrks-f6f472bb-net) in background
2023/07/19 16:08:08 [adaptor/cloud/azure] successfully deleted nic (podvm-nginx-6c48b665d4-tdrks-aec623b1-net) in background
2023/07/19 16:08:23 [adaptor/cloud/azure] successfully deleted nic (podvm-nginx-6c48b665d4-tdrks-c0ef99ca-net) in background
```

**Comment by surajssd** [comment]
Is this point we think about investing in using the Azure operator https://github.com/Azure/azure-service-operator ?

**Review by mkulke — APPROVED** [review]
In all my nic-leaking test cases things are cleaned up now eventually.

Thanks a ton for addressing this 🌺

**Pull request merged**
