### PR TITLE
podvm: Remove OPA from build

### PR DESCRIPTION
**Pull request by stevenhorsman**
Now we have switched to the `main` version of kata-agent, where regorus is being used to enforce policy,
we can remove OPA from the podvm image

### CODE REVIEW

**Review by mkulke — APPROVED** [review]

**Comment by bpradipt** [comment]
@stevenhorsman should this be also removed - https://github.com/confidential-containers/cloud-api-adaptor/blob/main/src/cloud-api-adaptor/podvm/files/etc/systemd/system/kata-opa.service ?

**Comment by stevenhorsman** [comment]
> @stevenhorsman should this be also removed - https://github.com/confidential-containers/cloud-api-adaptor/blob/main/src/cloud-api-adaptor/podvm/files/etc/systemd/system/kata-opa.service ?

Yes - thanks for the spot. I'll sort that now

**Comment by stevenhorsman** [comment]
> > @stevenhorsman should this be also removed - https://github.com/confidential-containers/cloud-api-adaptor/blob/main/src/cloud-api-adaptor/podvm/files/etc/systemd/system/kata-opa.service ?
> 
> Yes - thanks for the spot. I'll sort that now

I've added the kata-opa.service related removals in 79f852913ff6bf90ca04811ebd9bc343ccb9f63e for easier review, but if people are happen I'll fixup it into the previous commit

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @stevenhorsman

**Comment by bpradipt** [comment]
> > > @stevenhorsman should this be also removed - https://github.com/confidential-containers/cloud-api-adaptor/blob/main/src/cloud-api-adaptor/podvm/files/etc/systemd/system/kata-opa.service ?
> > 
> > 
> > Yes - thanks for the spot. I'll sort that now
> 
> I've added the kata-opa.service related removals in [79f8529](https://github.com/confidential-containers/cloud-api-adaptor/commit/79f852913ff6bf90ca04811ebd9bc343ccb9f63e) for easier review, but if people are happen I'll fixup it into the previous commit

looks good.. you can squash the commits and hopefully the CI will be happy post that

**Pull request merged**
