### PR TITLE
E2E: fix document for libvirt e2e test

### LINKED ISSUE #682: E2E, the README.md file for E2E file need be updated.
E2E, the README.md file for E2E file need be updated.
- [Created an end-to-end environment for testing and development](https://github.com/confidential-containers/cloud-api-adaptor/tree/staging/libvirt)
```bash
root@peer-pod1:~/cloud-api-adaptor# kcli list kube
+-----------+---------+-----------+-----------------------------------------+
|  Cluster  |   Type  |    Plan   |                   Vms                   |
+-----------+---------+-----------+-----------------------------------------+
| peer-pods | generic | peer-pods | peer-pods-ctlplane-0,peer-pods-worker-0 |
+-----------+---------+-----------+-----------------------------------------+
root@peer-pod1:~/cloud-api-adaptor# kubectl get nodes
NAME                   STATUS   ROLES           AGE   VERSION
peer-pods-ctlplane-0   Ready    control-plane   35m   v1.26.2
peer-pods-worker-0     Ready    worker          32m   v1.26.2
root@peer-pod1:~/cloud-api-adaptor# virsh -c qemu:///system list
 Id   Name                   State
--------------------------------------
 1    peer-pods-ctlplane-0   running
 2    peer-pods-worker-0     running
```
-  Follow the https://github.com/confidential-containers/cloud-api-adaptor/tree/staging/test/e2e try to run the e2e test base on libvirt, got the test result as:
```bash
root@peer-pod1:~/cloud-api-adaptor# CLOUD_PROVIDER=libvirt make test-e2e
go test -v  -ldflags="-X 'github.com/confidential-containers/cloud-api-adaptor/cmd.VERSION=unknown' -X 'github.com/confidential-containers/cloud-api-adaptor/cmd.COMMIT=cbcc961d6721c77a1c9e0c446ddfdcc3002e2076-dirty'" -tags=aws,azure,ibmcloud,vsphere,libvirt -timeout 20m -count=1 ./test/e2e
Do setup
Deploy the Cloud API Adaptor
Install the controller manager
Wait for the cc-operator-controller-manager deployment be available
Install CoCo and cloud-api-adaptor
Wait for the pod cc-operator-daemon-install-tprdx be ready
Wait for the pod cloud-api-adaptor-daemonset-libvirt-5mrqm be ready
Wait for the kata runtimeclass be created
=== RUN   TestAws
    env.go:230: No test testFeatures provided, skipping test
--- PASS: TestAws (0.00s)
=== RUN   TestCreateSimplePodAzure
    azure_test.go:65: AZURE_SUBSCRIPTION_ID was not set
--- FAIL: TestCreateSimplePodAzure (0.00s)
=== RUN   TestCreateSimplePod
    ibmcloud_test.go:63: APIKEY was not set.
--- FAIL: TestCreateSimplePod (0.00s)
=== RUN   TestLibvirtCreateSimplePod
=== RUN   TestLibvirtCreateSimplePod/Simple_Peer_Pod
=== RUN   TestLibvirtCreateSimplePod/Simple_Peer_Pod/PodVM_is_created
--- PASS: TestLibvirtCreateSimplePod (60.04s)
    --- PASS: TestLibvirtCreateSimplePod/Simple_Peer_Pod (60.04s)
        --- PASS: TestLibvirtCreateSimplePod/Simple_Peer_Pod/PodVM_is_created (0.00s)
FAIL
Delete the Cloud API Adaptor installation
Uninstall CoCo and cloud-api-adaptor
Uninstall the controller manager
Wait for the cc-operator-controller-manager deployment be deleted
FAIL	github.com/confidential-containers/cloud-api-adaptor/test/e2e	281.870s
FAIL
make: *** [Makefile:85: test-e2e] Error 1
```
We set the `CLOUD_PROVIDER` to libvirt, but the e2e test cases for other provider are executed too.

The expected result should looks like:
```bash
root@peer-pod1:~/cloud-api-adaptor# go test -v  -ldflags="-X 'github.com/confidential-containers/cloud-api-adaptor/cmd.VERSION=unknown' -X 'github.com/confidential-containers/cloud-api-adaptor/cmd.COMMIT=cbcc961d6721c77a1c9e0c446ddfdcc3002e2076-dirty'" -tags=libvirt -timeout 20m -count=1 ./test/e2e
Do setup
Deploy the Cloud API Adaptor
Install the controller manager
Wait for the cc-operator-controller-manager deployment be available
Install CoCo and cloud-api-adaptor
Wait for the pod cc-operator-daemon-install-2xgdq be ready
Wait for the pod cloud-api-adaptor-daemonset-libvirt-xdjhz be ready
Wait for the kata runtimeclass be created
=== RUN   TestLibvirtCreateSimplePod
=== RUN   TestLibvirtCreateSimplePod/Simple_Peer_Pod
=== RUN   TestLibvirtCreateSimplePod/Simple_Peer_Pod/PodVM_is_created
--- PASS: TestLibvirtCreateSimplePod (55.04s)
    --- PASS: TestLibvirtCreateSimplePod/Simple_Peer_Pod (55.04s)
        --- PASS: TestLibvirtCreateSimplePod/Simple_Peer_Pod/PodVM_is_created (0.00s)
PASS
Delete the Cloud API Adaptor installation
Uninstall CoCo and cloud-api-adaptor
Uninstall the controller manager
Wait for the cc-operator-controller-manager deployment be deleted
ok  	github.com/confidential-containers/cloud-api-adaptor/test/e2e	266.871s
```
Or
```bash
root@peer-pod1:~/cloud-api-adaptor# BUILTIN_CLOUD_PROVIDERS=libvirt make test-e2e
go test -v  -ldflags="-X 'github.com/confidential-containers/cloud-api-adaptor/cmd.VERSION=unknown' -X 'github.com/confidential-containers/cloud-api-adaptor/cmd.COMMIT=cbcc961d6721c77a1c9e0c446ddfdcc3002e2076-dirty'" -tags=libvirt -timeout 20m -count=1 ./test/e2e
Do setup
Deploy the Cloud API Adaptor
Install the controller manager
Wait for the cc-operator-controller-manager deployment be available
Install CoCo and cloud-api-adaptor
Wait for the pod cc-operator-daemon-install-7vcqv be ready
Wait for the pod cloud-api-adaptor-daemonset-libvirt-6z6js be ready
Wait for the kata runtimeclass be created
=== RUN   TestLibvirtCreateSimplePod
=== RUN   TestLibvirtCreateSimplePod/Simple_Peer_Pod
=== RUN   TestLibvirtCreateSimplePod/Simple_Peer_Pod/PodVM_is_created
--- PASS: TestLibvirtCreateSimplePod (55.04s)
    --- PASS: TestLibvirtCreateSimplePod/Simple_Peer_Pod (55.04s)
        --- PASS: TestLibvirtCreateSimplePod/Simple_Peer_Pod/PodVM_is_created (0.00s)
PASS
Delete the Cloud API Adaptor installation
Uninstall CoCo and cloud-api-adaptor
Uninstall the controller manager
Wait for the cc-operator-controller-manager deployment be deleted
ok  	github.com/confidential-containers/cloud-api-adaptor/test/e2e	271.871s

```

### PR DESCRIPTION
**Pull request by liudalibj**
fixes #682

Signed-off-by: Da Li Liu <liudali@cn.ibm.com>

### CODE REVIEW

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @liudalibj

**Review by huoqifeng — APPROVED** [review]
/lgtm, thanks @liudalibj

**Comment by stevenhorsman** [comment]
@liudalibj - hey DaLi, sorry it took me a while to set up my environment review this and it's already merged, but I hit an issues with it locally:
```
# TEST_E2E_PROVISION=yes BUILTIN_CLOUD_PROVIDERS=libvirt make test-e2e
go: downloading github.com/Azure/azure-sdk-for-go/sdk/azcore v1.1.2
...
go: downloading github.com/josharian/intern v1.0.0
CLOUD_PROVIDER should be exported in the environment
FAIL	github.com/confidential-containers/cloud-api-adaptor/test/e2e	0.030s
FAIL
make: *** [Makefile:85: test-e2e] Error 1
```
Have you got any ideas what I might have done wrong if this worked for you?

**Comment by liudalibj** [comment]
> @liudalibj - hey DaLi, sorry it took me a while to set up my environment review this and it's already merged, but I hit an issues with it locally:
> 
> ```
> # TEST_E2E_PROVISION=yes BUILTIN_CLOUD_PROVIDERS=libvirt make test-e2e
> go: downloading github.com/Azure/azure-sdk-for-go/sdk/azcore v1.1.2
> ...
> go: downloading github.com/josharian/intern v1.0.0
> CLOUD_PROVIDER should be exported in the environment
> FAIL	github.com/confidential-containers/cloud-api-adaptor/test/e2e	0.030s
> FAIL
> make: *** [Makefile:85: test-e2e] Error 1
> ```
> 
> Have you got any ideas what I might have done wrong if this worked for you?

@stevenhorsman Thanks the find, in my dev environment, when I prepare the libvirt test/dev cluster in the first step, I already follow the document export the environment `export CLOUD_PROVIDER=libvirt`,sorry for missed it in the e2e test document. I create a new PR https://github.com/confidential-containers/cloud-api-adaptor/pull/687 to fix the e2e test issue, it should be a better fix, as we should only can run the e2e test cases for one provider at the same time.

**Pull request merged**
