### PR TITLE
aws: use common makefile for generating the AMI image

### PR DESCRIPTION
**Pull request by bpradipt**
Fixes: #399
Signed-off-by: Pradipta Banerjee <pradipta.banerjee@gmail.com>

### CODE REVIEW

**Review by stevenhorsman — DISMISSED** [review]
LGTM. Thanks @bpradipt!

**Comment by snir911** [comment]
Hi, i just noticed when i use the podvm image created by the common makefile for aws running a pod hits an error:
```
2022/12/04 10:10:45 [adaptor/proxy] CreateContainer: successfully pulled image "registry.fedoraproject.org/fedora:latest"
2022/12/04 10:10:45 [adaptor/proxy] CreateContainer fails: rpc error: code = Internal desc = No such file or directory (os error 2)
```
```
Warning  Failed          65s   kubelet            Error: failed to create containerd task: failed to create shim task: No such file or directory (os error 2): unknown
```
Additionally I'd update the README.md to use the new `image` makefile target
(I also noticed i didn't modify the common foldor to copy the auth file but I'll do it in separate)

**Comment by bpradipt** [comment]
> Hi, i just noticed when i use the podvm image created by the common makefile for aws running a pod hits an error:
> 
> ```
> 2022/12/04 10:10:45 [adaptor/proxy] CreateContainer: successfully pulled image "registry.fedoraproject.org/fedora:latest"
> 2022/12/04 10:10:45 [adaptor/proxy] CreateContainer fails: rpc error: code = Internal desc = No such file or directory (os error 2)
> ```
> 
> ```
> Warning  Failed          65s   kubelet            Error: failed to create containerd task: failed to create shim task: No such file or directory (os error 2): unknown
> ```
> 
> Additionally I'd update the README.md to use the new `image` makefile target (I also noticed i didn't modify the common foldor to copy the auth file but I'll do it in separate)

Good catch @snir911 . I'll update the README for now.

**Comment by bpradipt** [comment]
@snir911 did you VM creation succeed in AWS or still having the issue ?

**Comment by snir911** [comment]
@bpradipt issue still exist, i have two ami images, one created on this branch and one on upstream, the one created from this branch keeps failing with the same error

**Comment by snir911** [comment]
@bpradipt probably the issue is because we're the missing the `ExecStartPre=-umount /sys/fs/cgroup/misc` workaround needed for the aws kernel

**Comment by bpradipt** [comment]
> @bpradipt probably the issue is because we're missing the `ExecStartPre=-umount /sys/fs/cgroup/misc` workaround needed for the aws kernel

Yes.. this entry is missing in the common files. This is safe to be added in the common files

**Review by snir911 — APPROVED** [review]

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks Pradipta!

**Pull request merged**
