### PR TITLE
azure-docs: Minor changes to instructions

### PR DESCRIPTION
**Pull request by surajssd**
This commit makes it even more easier and hands-off approach for the user when following the Azure documentation.

### CODE REVIEW

**Comment by bpradipt** [comment]
The instructions are pretty straightforward now, however faced two issues

```
2023/09/21 08:03:45 [adaptor/cloud/azure] using workload identity
cloud-api-adaptor: getting next page of VM sizes: GET https://management.azure.com/subscriptions/<subscription>/providers/Microsoft.Compute/locations/eastus/vmSizes
--------------------------------------------------------------------------------
RESPONSE 403: 403 Forbidden
ERROR CODE: AuthorizationFailed
--------------------------------------------------------------------------------
{
  "error": {
    "code": "AuthorizationFailed",
    "message": "The client '<client-id>' with object id '<object-id>' does not have authorization to perform action 'Microsoft.Compute/locations/vmSizes/read' over scope '/subscriptions/<subscription>' or the scope is invalid. If access was recently granted, please refresh your credentials."
  }
}
```

Second one, is on the daily images. The latest image version is `2023.09.15`. Do you also want to refer to an available image and update instructions to find latest daily image?

**Comment by surajssd** [comment]
> The instructions are pretty straightforward now, however faced two issues

Is this the scenario where you don't provide the vm size?

**Comment by surajssd** [comment]
> > Is this the scenario where you don't provide the VM size? Right now, the permissions are super limited, and this seems like it is trying to access the whole subscription level.
> 
> No, I did use `AZURE_INSTANCE_SIZE: Standard_DC2as_v5`. Infact I just followed the instructions to setup the cluster. Wondering if I missed something. Did you ever face this recently ?

I have faced this exact error in the past. But back then I got around by giving sub wide permission to unblock myself. But I am not sure why this error shows up intermittently. I tested the instructions yesterday and Iago did that the day before but didn't have this problem. I will test these instructions with another Azure subscription that I have and see if things work.

**Comment by surajssd** [comment]
@bpradipt I tried on my personal account too and I see the following:

```bash
2023/09/21 15:29:25 [adaptor/cloud/azure] using workload identity
2023/09/21 15:29:27 [adaptor/cloud/azure] instanceSizeSpecList ([{Standard_DC2as_v5 2 8192  0}])
```

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @surajssd

**Review by mkulke — APPROVED** [review]

**Pull request merged**
