### PR TITLE
versions: update kbs image tag

### PR DESCRIPTION
**Pull request by kartikjoshi21**
Update kbs image tag to make it compatible with current guest component and caa.

Fixes: #1785

### CODE REVIEW

**Comment by stevenhorsman** [comment]
@kartikjoshi21 - is this required for the 0.8.1 release? or something for after that?

**Comment by mkulke** [comment]
> @kartikjoshi21 - is this required for the 0.8.1 release? or something for after that?

I wouldn't say it's required. this is part of the kbs remote-attestation tests that are still WIP

**Review by mkulke — COMMENTED** [review]
Can you quickly explain why exactly this hash?

**Review by surajssd — APPROVED** [review]

**Comment by surajssd** [comment]
> Can you quickly explain why exactly this hash?

I think it is one of those images that gets built on each merge to main. And this is the one compatible with the current guest-components version.

**Comment by huoqifeng** [comment]
I'm not sure whether this is right PR to discuss but we know KBS consists of the resource-service, attestation-service and the RVPS-service. Is the new tag (I guess it'll be deployed when do e2e test) includes all these services?

**Comment by kartikjoshi21** [comment]
> I'm not sure whether this is right PR to discuss but we know KBS consists of the resource-service, attestation-service and the RVPS-service. Is the new tag (I guess it'll be deployed when do e2e test) includes all these services?

This is trustee repository commit tag which is compatible with current guest component version. It is used to clone trustee repo to working directory of test and to fetch kbs image.

**Comment by mkulke** [comment]
> I'm not sure whether this is right PR to discuss but we know KBS consists of the resource-service, attestation-service and the RVPS-service. Is the new tag (I guess it'll be deployed when do e2e test) includes all these services?

yes it should

**Review by mkulke — APPROVED** [review]

**Pull request merged**
