### PR TITLE
Update operator config to include selinux

### PR DESCRIPTION
**Pull request by stevenhorsman**
Make config updates based on
https://github.com/kata-containers/kata-containers/pull/4813

Fixes: #438

Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Review by fidencio — DISMISSED** [review]
lgtm, thanks @stevenhorsman!

**Comment by stevenhorsman** [comment]
For full transparency I'm a bit unsure on what setting we should have for `disable_guest_selinux=true` As it defaults to true I don't think it is harmful, but if we hit problems we might need to flip it.

**Comment by bpradipt** [comment]
> @bpradipt, can you, Snir, or someone give this a test please? Our ibm cloud operator 'support' seems to have gone a bit stale, so I don't have an easy way to try it and out and don't have time to debug that right now. Thanks!

Yes, will test it out.

**Comment by stevenhorsman** [comment]
Hey @bpradipt - hold fire on testing this for now - I think there is also a bug in kata-containers that need fixing first, I'll keep you updated when I learn more.

**Comment by stevenhorsman** [comment]
The kata-containers PR I has been created https://github.com/kata-containers/kata-containers/pull/5937 - this is a pre-req for this PR as it won't work without it. Sorry for the confusion.

**Comment by stevenhorsman** [comment]
Now https://github.com/kata-containers/kata-containers/pull/5937 has merged I think this should be ready to tests as long as the latest kata-containers `CCv0` code is used. Thanks!

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @stevenhorsman

**Review by huoqifeng — APPROVED** [review]
/lgtm thanks @stevenhorsman

**Pull request merged**
