### PR TITLE
image: pull image via remote-snapshotter

### PR DESCRIPTION
**Pull request by huoqifeng**
Fixes: #1511

Signed-off-by: Qi Feng Huo <huoqif@cn.ibm.com>

### CODE REVIEW

**Comment by huoqifeng** [comment]
Testes the code like this.
- Scenario 1 - Use nydus-snapshotter
In this scenario:
Start nydus
```
systemd-cat -t snapshotter /usr/local/bin/containerd-nydus-grpc --config /usr/local/share/nydus-snapshotter/config-coco-guest-pulling.toml --log-to-stdout --log-level debug &
```
Change the containerd to use 1.7.6, like:
```
cat /etc/systemd/system/containerd.service.d/containerd-for
	[Service]
	ExecStart=
	ExecStart=/usr/local/bin/containerd
```
Change containerd toml to use nydus for kata and kata-remote
```
cat /etc/containerd/config.toml
[proxy_plugins]
  [proxy_plugins.nydus]
    type = "snapshot"
    address = "/run/containerd-nydus/containerd-nydus-grpc.sock"
..
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata]
  runtime_type = "io.containerd.kata.v2"
  snapshotter = "nydus"
  privileged_without_host_devices = true
  pod_annotations = ["io.katacontainers.*"]
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration.toml"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-remote]
  runtime_type = "io.containerd.kata-remote.v2"
  snapshotter = "nydus"
  privileged_without_host_devices = true
  pod_annotations = ["io.katacontainers.*"]
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-remote.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-remote.toml"
```
Restart containerd service after settings change
```
systemctl daemon-reload
systemctl restart containerd
systemctl status containerd
```
Verify the containerd:
```
kubectl get nodes -o wide
NAME                          STATUS   ROLES           AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
huoqif-s390x-self-jp-node-0   Ready    control-plane   3d15h   v1.28.2   10.244.64.5   <none>        Ubuntu 20.04.6 LTS   5.4.0-125-generic   containerd://1.7.6
huoqif-s390x-self-jp-node-1   Ready    <none>          3d15h   v1.28.2   10.244.64.4   <none>        Ubuntu 20.04.6 LTS   5.4.0-125-generic   containerd://1.7.6
``` 
Start caa as a service
```
exec ./cloud-api-adaptor ibmcloud \
   -iam-service-url "${IBMCLOUD_IAM_ENDPOINT}" \
   -vpc-service-url "${IBMCLOUD_VPC_ENDPOINT}" \
   -resource-group-id "${IBMCLOUD_RESOURCE_GROUP_
   -key-id "${IBMCLOUD_SSH_KEY_ID}" \
   -image-id "${IBMCLOUD_PODVM_IMAGE_ID}" \
   -profile-name "${IBMCLOUD_PODVM_INSTANCE_PROFI
   -profile-list "${IBMCLOUD_PODVM_INSTANCE_PROFI
   -zone-name "${IBMCLOUD_ZONE}" \
   -primary-subnet-id "${IBMCLOUD_VPC_SUBNET_ID}"
   -primary-security-group-id "${IBMCLOUD_VPC_SG_
   -vpc-id "${IBMCLOUD_VPC_ID}" \
   -pods-dir /run/peerpod/pods \
   -cri-runtime-endpoint /var/run/containerd/cont
   -socket /run/peerpod/hypervisor.sock \
   > /var/log/cloud-api-adaptor.log 2>&1 &
```
Test create a PeerPod and tail the log
```
2023/10/11 14:35:35 [podnetwork] routes on netns /var/run/netns/cni-61892902-3b8b-05fe-97f8-559d7560afb0
2023/10/11 14:35:35 [podnetwork]     default via 172.20.1.1 dev eth0
2023/10/11 14:35:35 [podnetwork]     172.20.0.0/16 via 172.20.1.1 dev eth0
2023/10/11 14:35:35 [adaptor/cloud] Credentials file is not in a valid Json format, ignored
2023/10/11 14:35:35 [adaptor/cloud] stored /run/peerpod/pods/23f3c16bd7118748a85f8d2405de1ba108825e56a0ac9433fb8ed5a1e2b109ad/daemon.json
2023/10/11 14:35:35 [adaptor/cloud] create a sandbox 23f3c16bd7118748a85f8d2405de1ba108825e56a0ac9433fb8ed5a1e2b109ad for pod nginx2 in namespace default (netns: /var/run/netns/cni-61892902-3b8b-05fe-97f8-559d7560afb0)
Using default instance type ("bz2-2x8")
2023/10/11 14:35:35 [adaptor/cloud/ibmcloud] selected image with ID <r022-da4b5a42-3743-485e-a581-94887c783a5d> out of 2 images
2023/10/11 14:35:35 [adaptor/cloud/ibmcloud] CreateInstance: name: "podvm-nginx2-23f3c16b"
2023/10/11 14:35:40 [adaptor/cloud/ibmcloud] podNodeIP[0]=10.244.64.29
2023/10/11 14:35:40 [adaptor/cloud] created an instance podvm-nginx2-23f3c16b for sandbox 23f3c16bd7118748a85f8d2405de1ba108825e56a0ac9433fb8ed5a1e2b109ad
2023/10/11 14:35:40 [tunneler/vxlan] vxlan ppvxlan1 (remote 10.244.64.29:4789, id: 555001) created at /proc/1397166/task/1397180/ns/net
2023/10/11 14:35:40 [tunneler/vxlan] vxlan ppvxlan1 created at /proc/1397166/task/1397180/ns/net
2023/10/11 14:35:40 [tunneler/vxlan] vxlan ppvxlan1 is moved to /var/run/netns/cni-61892902-3b8b-05fe-97f8-559d7560afb0
2023/10/11 14:35:40 [tunneler/vxlan] Add tc redirect filters between eth0 and vxlan1 on pod network namespace /var/run/netns/cni-61892902-3b8b-05fe-97f8-559d7560afb0
2023/10/11 14:35:40 [adaptor/proxy] Listening on /run/peerpod/pods/23f3c16bd7118748a85f8d2405de1ba108825e56a0ac9433fb8ed5a1e2b109ad/agent.ttrpc
2023/10/11 14:35:40 [adaptor/proxy] established cri uds connection to /var/run/containerd/containerd.sock
2023/10/11 14:35:40 [adaptor/proxy] Trying to establish agent proxy connection to 10.244.64.29:15150
2023/10/11 14:35:53 [adaptor/proxy] established agent proxy connection to 10.244.64.29:15150
2023/10/11 14:35:53 [adaptor/cloud] agent proxy is ready
2023/10/11 14:35:53 [adaptor/proxy] CreateSandbox: hostname:nginx2 sandboxId:23f3c16bd7118748a85f8d2405de1ba108825e56a0ac9433fb8ed5a1e2b109ad
2023/10/11 14:35:53 [adaptor/proxy]     storages:
2023/10/11 14:35:53 [adaptor/proxy]         mountpoint:/run/kata-containers/sandbox/shm source:shm fstype:tmpfs driver:ephemeral
2023/10/11 14:36:00 [adaptor/proxy] CreateContainer: containerID:23f3c16bd7118748a85f8d2405de1ba108825e56a0ac9433fb8ed5a1e2b109ad
2023/10/11 14:36:00 [adaptor/proxy]     mounts:
2023/10/11 14:36:00 [adaptor/proxy]         destination:/proc source:proc type:proc
2023/10/11 14:36:00 [adaptor/proxy]         destination:/dev source:tmpfs type:tmpfs
2023/10/11 14:36:00 [adaptor/proxy]         destination:/dev/pts source:devpts type:devpts
2023/10/11 14:36:00 [adaptor/proxy]         destination:/dev/mqueue source:mqueue type:mqueue
2023/10/11 14:36:00 [adaptor/proxy]         destination:/sys source:sysfs type:sysfs
2023/10/11 14:36:00 [adaptor/proxy]         destination:/dev/shm source:/run/kata-containers/sandbox/shm type:bind
2023/10/11 14:36:00 [adaptor/proxy]         destination:/etc/resolv.conf source:/run/kata-containers/shared/containers/23f3c16bd7118748a85f8d2405de1ba108825e56a0ac9433fb8ed5a1e2b109ad-69eaf30011d54a75-resolv.conf type:bind
2023/10/11 14:36:00 [adaptor/proxy]     annotations:
2023/10/11 14:36:00 [adaptor/proxy]         io.kubernetes.cri.sandbox-cpu-period: 100000
2023/10/11 14:36:00 [adaptor/proxy]         io.kubernetes.cri.sandbox-uid: 8468637f-b6fb-4d1d-a92b-08c86c685e23
2023/10/11 14:36:00 [adaptor/proxy]         io.kubernetes.cri.sandbox-cpu-shares: 2
2023/10/11 14:36:00 [adaptor/proxy]         io.katacontainers.pkg.oci.bundle_path: /run/containerd/io.containerd.runtime.v2.task/k8s.io/23f3c16bd7118748a85f8d2405de1ba108825e56a0ac9433fb8ed5a1e2b109ad
2023/10/11 14:36:00 [adaptor/proxy]         io.kubernetes.cri.sandbox-log-directory: /var/log/pods/default_nginx2_8468637f-b6fb-4d1d-a92b-08c86c685e23
2023/10/11 14:36:00 [adaptor/proxy]         io.katacontainers.pkg.oci.container_type: pod_sandbox
2023/10/11 14:36:00 [adaptor/proxy]         io.kubernetes.cri.sandbox-memory: 0
2023/10/11 14:36:00 [adaptor/proxy]         io.kubernetes.cri.sandbox-namespace: default
2023/10/11 14:36:00 [adaptor/proxy]         io.kubernetes.cri.container-type: sandbox
2023/10/11 14:36:00 [adaptor/proxy]         nerdctl/network-namespace: /var/run/netns/cni-61892902-3b8b-05fe-97f8-559d7560afb0
2023/10/11 14:36:00 [adaptor/proxy]         io.kubernetes.cri.sandbox-id: 23f3c16bd7118748a85f8d2405de1ba108825e56a0ac9433fb8ed5a1e2b109ad
2023/10/11 14:36:00 [adaptor/proxy]         io.kubernetes.cri.sandbox-name: nginx2
2023/10/11 14:36:00 [adaptor/proxy]         io.kubernetes.cri.sandbox-cpu-quota: 0
2023/10/11 14:36:00 [adaptor/proxy]     storages:
2023/10/11 14:36:00 [adaptor/proxy]         mount_point:/run/kata-containers/23f3c16bd7118748a85f8d2405de1ba108825e56a0ac9433fb8ed5a1e2b109ad/rootfs source:pause fstype:overlay driver:image_guest_pull
2023/10/11 14:36:00 [adaptor/proxy] CreateContainer: Ignoring PullImage before CreateContainer (cid: "23f3c16bd7118748a85f8d2405de1ba108825e56a0ac9433fb8ed5a1e2b109ad")
2023/10/11 14:36:00 [adaptor/proxy] StartContainer: containerID:23f3c16bd7118748a85f8d2405de1ba108825e56a0ac9433fb8ed5a1e2b109ad
2023/10/11 14:36:02 [adaptor/proxy] CreateContainer: containerID:e71f66fb91ce34ff31d1e2ab33a53f40b54527feff83a81b68bcfd7242310ce0
2023/10/11 14:36:02 [adaptor/proxy]     mounts:
2023/10/11 14:36:02 [adaptor/proxy]         destination:/proc source:proc type:proc
2023/10/11 14:36:02 [adaptor/proxy]         destination:/dev source:tmpfs type:tmpfs
2023/10/11 14:36:02 [adaptor/proxy]         destination:/dev/pts source:devpts type:devpts
2023/10/11 14:36:02 [adaptor/proxy]         destination:/dev/mqueue source:mqueue type:mqueue
2023/10/11 14:36:02 [adaptor/proxy]         destination:/sys source:sysfs type:sysfs
2023/10/11 14:36:02 [adaptor/proxy]         destination:/sys/fs/cgroup source:cgroup type:cgroup
2023/10/11 14:36:02 [adaptor/proxy]         destination:/etc/config source:/run/kata-containers/shared/containers/e71f66fb91ce34ff31d1e2ab33a53f40b54527feff83a81b68bcfd7242310ce0-69dde3bbfe3b6ddc-config type:bind
2023/10/11 14:36:02 [adaptor/proxy]         destination:/sealed/etc/secret source:/run/kata-containers/shared/containers/e71f66fb91ce34ff31d1e2ab33a53f40b54527feff83a81b68bcfd7242310ce0-e3585bcfbd998589-secret type:bind
2023/10/11 14:36:02 [adaptor/proxy]         destination:/etc/hosts source:/run/kata-containers/shared/containers/e71f66fb91ce34ff31d1e2ab33a53f40b54527feff83a81b68bcfd7242310ce0-b5249e2784210d2c-hosts type:bind
2023/10/11 14:36:02 [adaptor/proxy]         destination:/dev/termination-log source:/run/kata-containers/shared/containers/e71f66fb91ce34ff31d1e2ab33a53f40b54527feff83a81b68bcfd7242310ce0-5b564fa9137dfcca-termination-log type:bind
2023/10/11 14:36:02 [adaptor/proxy]         destination:/etc/hostname source:/run/kata-containers/shared/containers/e71f66fb91ce34ff31d1e2ab33a53f40b54527feff83a81b68bcfd7242310ce0-12ca5110a830ab03-hostname type:bind
2023/10/11 14:36:02 [adaptor/proxy]         destination:/etc/resolv.conf source:/run/kata-containers/shared/containers/e71f66fb91ce34ff31d1e2ab33a53f40b54527feff83a81b68bcfd7242310ce0-aa1ca6d3420eb203-resolv.conf type:bind
2023/10/11 14:36:02 [adaptor/proxy]         destination:/dev/shm source:/run/kata-containers/sandbox/shm type:bind
2023/10/11 14:36:02 [adaptor/proxy]         destination:/var/run/secrets/kubernetes.io/serviceaccount source:/run/kata-containers/shared/containers/e71f66fb91ce34ff31d1e2ab33a53f40b54527feff83a81b68bcfd7242310ce0-00b580fab0770c91-serviceaccount type:bind
2023/10/11 14:36:02 [adaptor/proxy]     annotations:
2023/10/11 14:36:02 [adaptor/proxy]         io.kubernetes.cri.sandbox-uid: 8468637f-b6fb-4d1d-a92b-08c86c685e23
2023/10/11 14:36:02 [adaptor/proxy]         io.kubernetes.cri.sandbox-name: nginx2
2023/10/11 14:36:02 [adaptor/proxy]         io.katacontainers.pkg.oci.container_type: pod_container
2023/10/11 14:36:02 [adaptor/proxy]         io.kubernetes.cri.sandbox-namespace: default
2023/10/11 14:36:02 [adaptor/proxy]         io.kubernetes.cri.container-name: nginx2
2023/10/11 14:36:02 [adaptor/proxy]         io.kubernetes.cri.image-name: docker.io/library/nginx:latest
2023/10/11 14:36:02 [adaptor/proxy]         io.kubernetes.cri.container-type: container
2023/10/11 14:36:02 [adaptor/proxy]         io.katacontainers.pkg.oci.bundle_path: /run/containerd/io.containerd.runtime.v2.task/k8s.io/e71f66fb91ce34ff31d1e2ab33a53f40b54527feff83a81b68bcfd7242310ce0
2023/10/11 14:36:02 [adaptor/proxy]         io.kubernetes.cri.sandbox-id: 23f3c16bd7118748a85f8d2405de1ba108825e56a0ac9433fb8ed5a1e2b109ad
2023/10/11 14:36:02 [adaptor/proxy]     storages:
2023/10/11 14:36:02 [adaptor/proxy]         mount_point:/run/kata-containers/e71f66fb91ce34ff31d1e2ab33a53f40b54527feff83a81b68bcfd7242310ce0/rootfs source:docker.io/library/nginx:latest fstype:overlay driver:image_guest_pull
2023/10/11 14:36:02 [adaptor/proxy] CreateContainer: Ignoring PullImage before CreateContainer (cid: "e71f66fb91ce34ff31d1e2ab33a53f40b54527feff83a81b68bcfd7242310ce0")
2023/10/11 14:36:07 [adaptor/proxy] StartContainer: containerID:e71f66fb91ce34ff31d1e2ab33a53f40b54527feff83a81b68bcfd7242310ce0
```

- Scenario 2 - Use forked containerd without nydus as before
Roll back the change and create a PeerPod
```
# kubectl get nodes -o wide
NAME                          STATUS   ROLES           AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
huoqif-s390x-self-jp-node-0   Ready    control-plane   3d15h   v1.28.2   10.244.64.5   <none>        Ubuntu 20.04.6 LTS   5.4.0-125-generic   containerd://1.7.6
huoqif-s390x-self-jp-node-1   Ready    <none>          3d15h   v1.28.2   10.244.64.4   <none>        Ubuntu 20.04.6 LTS   5.4.0-125-generic   containerd://1.6.8.2
```
then tails the log
```
2023/10/12 00:16:36 [podnetwork] routes on netns /var/run/netns/cni-14007818-52c9-4bb5-ffef-5b73f9051340
2023/10/12 00:16:36 [podnetwork]     default via 172.20.1.1 dev eth0
2023/10/12 00:16:36 [podnetwork]     172.20.0.0/16 via 172.20.1.1 dev eth0
2023/10/12 00:16:36 [adaptor/cloud] Credentials file is not in a valid Json format, ignored
2023/10/12 00:16:36 [adaptor/cloud] stored /run/peerpod/pods/a42f354c7c73f95edd9dcedefb5f9ed5d7ef53678ef9ce821150d072957fd1f9/daemon.json
2023/10/12 00:16:36 [adaptor/cloud] create a sandbox a42f354c7c73f95edd9dcedefb5f9ed5d7ef53678ef9ce821150d072957fd1f9 for pod nginx in namespace default (netns: /var/run/netns/cni-14007818-52c9-4bb5-ffef-5b73f9051340)
Using default instance type ("bz2-2x8")
2023/10/12 00:16:36 [adaptor/cloud/ibmcloud] selected image with ID <r022-da4b5a42-3743-485e-a581-94887c783a5d> out of 2 images
2023/10/12 00:16:36 [adaptor/cloud/ibmcloud] CreateInstance: name: "podvm-nginx-a42f354c"
2023/10/12 00:16:44 [adaptor/cloud/ibmcloud] podNodeIP[0]=10.244.64.30
2023/10/12 00:16:44 [adaptor/cloud] created an instance podvm-nginx-a42f354c for sandbox a42f354c7c73f95edd9dcedefb5f9ed5d7ef53678ef9ce821150d072957fd1f9
2023/10/12 00:16:44 [tunneler/vxlan] vxlan ppvxlan1 (remote 10.244.64.30:4789, id: 555002) created at /proc/1397166/task/1397906/ns/net
2023/10/12 00:16:44 [tunneler/vxlan] vxlan ppvxlan1 created at /proc/1397166/task/1397906/ns/net
2023/10/12 00:16:44 [tunneler/vxlan] vxlan ppvxlan1 is moved to /var/run/netns/cni-14007818-52c9-4bb5-ffef-5b73f9051340
2023/10/12 00:16:44 [tunneler/vxlan] Add tc redirect filters between eth0 and vxlan1 on pod network namespace /var/run/netns/cni-14007818-52c9-4bb5-ffef-5b73f9051340
2023/10/12 00:16:44 [adaptor/proxy] Listening on /run/peerpod/pods/a42f354c7c73f95edd9dcedefb5f9ed5d7ef53678ef9ce821150d072957fd1f9/agent.ttrpc
2023/10/12 00:16:44 [adaptor/proxy] established cri uds connection to /var/run/containerd/containerd.sock
2023/10/12 00:16:44 [adaptor/proxy] Trying to establish agent proxy connection to 10.244.64.30:15150
2023/10/12 00:16:58 [adaptor/proxy] established agent proxy connection to 10.244.64.30:15150
2023/10/12 00:16:58 [adaptor/cloud] agent proxy is ready
2023/10/12 00:16:58 [adaptor/proxy] CreateSandbox: hostname:nginx sandboxId:a42f354c7c73f95edd9dcedefb5f9ed5d7ef53678ef9ce821150d072957fd1f9
2023/10/12 00:16:58 [adaptor/proxy]     storages:
2023/10/12 00:16:58 [adaptor/proxy]         mountpoint:/run/kata-containers/sandbox/shm source:shm fstype:tmpfs driver:ephemeral
2023/10/12 00:17:05 [adaptor/proxy] CreateContainer: containerID:a42f354c7c73f95edd9dcedefb5f9ed5d7ef53678ef9ce821150d072957fd1f9
2023/10/12 00:17:05 [adaptor/proxy]     mounts:
2023/10/12 00:17:05 [adaptor/proxy]         destination:/proc source:proc type:proc
2023/10/12 00:17:05 [adaptor/proxy]         destination:/dev source:tmpfs type:tmpfs
2023/10/12 00:17:05 [adaptor/proxy]         destination:/dev/pts source:devpts type:devpts
2023/10/12 00:17:05 [adaptor/proxy]         destination:/dev/shm source:/run/kata-containers/sandbox/shm type:bind
2023/10/12 00:17:05 [adaptor/proxy]         destination:/dev/mqueue source:mqueue type:mqueue
2023/10/12 00:17:05 [adaptor/proxy]         destination:/sys source:sysfs type:sysfs
2023/10/12 00:17:05 [adaptor/proxy]         destination:/dev/shm source:/run/kata-containers/sandbox/shm type:bind
2023/10/12 00:17:05 [adaptor/proxy]         destination:/etc/resolv.conf source:/run/kata-containers/shared/containers/a42f354c7c73f95edd9dcedefb5f9ed5d7ef53678ef9ce821150d072957fd1f9-4c495ac1a9d612b1-resolv.conf type:bind
2023/10/12 00:17:05 [adaptor/proxy]     annotations:
2023/10/12 00:17:05 [adaptor/proxy]         io.kubernetes.cri.sandbox-memory: 0
2023/10/12 00:17:05 [adaptor/proxy]         io.kubernetes.cri.sandbox-cpu-period: 100000
2023/10/12 00:17:05 [adaptor/proxy]         io.kubernetes.cri.sandbox-id: a42f354c7c73f95edd9dcedefb5f9ed5d7ef53678ef9ce821150d072957fd1f9
2023/10/12 00:17:05 [adaptor/proxy]         io.kubernetes.cri.sandbox-cpu-quota: 0
2023/10/12 00:17:05 [adaptor/proxy]         io.kubernetes.cri.container-type: sandbox
2023/10/12 00:17:05 [adaptor/proxy]         io.katacontainers.pkg.oci.bundle_path: /run/containerd/io.containerd.runtime.v2.task/k8s.io/a42f354c7c73f95edd9dcedefb5f9ed5d7ef53678ef9ce821150d072957fd1f9
2023/10/12 00:17:05 [adaptor/proxy]         io.kubernetes.cri.sandbox-name: nginx
2023/10/12 00:17:05 [adaptor/proxy]         io.katacontainers.pkg.oci.container_type: pod_sandbox
2023/10/12 00:17:05 [adaptor/proxy]         io.kubernetes.cri.sandbox-log-directory: /var/log/pods/default_nginx_91347765-82af-4249-a728-72e904fa2bcc
2023/10/12 00:17:05 [adaptor/proxy]         nerdctl/network-namespace: /var/run/netns/cni-14007818-52c9-4bb5-ffef-5b73f9051340
2023/10/12 00:17:05 [adaptor/proxy]         io.kubernetes.cri.sandbox-cpu-shares: 2
2023/10/12 00:17:05 [adaptor/proxy]         io.kubernetes.cri.sandbox-namespace: default
2023/10/12 00:17:05 [adaptor/proxy] getImageName: no pause image specified uses default pause image: registry.k8s.io/pause:3.7
2023/10/12 00:17:05 [adaptor/proxy] CreateContainer: calling PullImage for "registry.k8s.io/pause:3.7" before CreateContainer (cid: "a42f354c7c73f95edd9dcedefb5f9ed5d7ef53678ef9ce821150d072957fd1f9")
2023/10/12 00:17:06 [adaptor/proxy] CreateContainer: successfully pulled image "registry.k8s.io/pause:3.7"
2023/10/12 00:17:06 [adaptor/proxy] StartContainer: containerID:a42f354c7c73f95edd9dcedefb5f9ed5d7ef53678ef9ce821150d072957fd1f9
2023/10/12 00:17:09 [adaptor/proxy] CreateContainer: containerID:a85cbf02527556217f118860cea0d64e69676fea5ff7c1f7c8d1ae12711c386b
2023/10/12 00:17:09 [adaptor/proxy]     mounts:
2023/10/12 00:17:09 [adaptor/proxy]         destination:/proc source:proc type:proc
2023/10/12 00:17:09 [adaptor/proxy]         destination:/dev source:tmpfs type:tmpfs
2023/10/12 00:17:09 [adaptor/proxy]         destination:/dev/pts source:devpts type:devpts
2023/10/12 00:17:09 [adaptor/proxy]         destination:/dev/mqueue source:mqueue type:mqueue
2023/10/12 00:17:09 [adaptor/proxy]         destination:/sys source:sysfs type:sysfs
2023/10/12 00:17:09 [adaptor/proxy]         destination:/sys/fs/cgroup source:cgroup type:cgroup
2023/10/12 00:17:09 [adaptor/proxy]         destination:/etc/config source:/run/kata-containers/shared/containers/a85cbf02527556217f118860cea0d64e69676fea5ff7c1f7c8d1ae12711c386b-95a32e4a42d88732-config type:bind
2023/10/12 00:17:09 [adaptor/proxy]         destination:/sealed/etc/secret source:/run/kata-containers/shared/containers/a85cbf02527556217f118860cea0d64e69676fea5ff7c1f7c8d1ae12711c386b-1984634d3bf437e5-secret type:bind
2023/10/12 00:17:09 [adaptor/proxy]         destination:/etc/hosts source:/run/kata-containers/shared/containers/a85cbf02527556217f118860cea0d64e69676fea5ff7c1f7c8d1ae12711c386b-cc7afe0ac036a593-hosts type:bind
2023/10/12 00:17:09 [adaptor/proxy]         destination:/dev/termination-log source:/run/kata-containers/shared/containers/a85cbf02527556217f118860cea0d64e69676fea5ff7c1f7c8d1ae12711c386b-c1c72d30d7e9459c-termination-log type:bind
2023/10/12 00:17:09 [adaptor/proxy]         destination:/etc/hostname source:/run/kata-containers/shared/containers/a85cbf02527556217f118860cea0d64e69676fea5ff7c1f7c8d1ae12711c386b-c39fb0818450b6d6-hostname type:bind
2023/10/12 00:17:09 [adaptor/proxy]         destination:/etc/resolv.conf source:/run/kata-containers/shared/containers/a85cbf02527556217f118860cea0d64e69676fea5ff7c1f7c8d1ae12711c386b-09fb561bb1e94cf1-resolv.conf type:bind
2023/10/12 00:17:09 [adaptor/proxy]         destination:/dev/shm source:/run/kata-containers/sandbox/shm type:bind
2023/10/12 00:17:09 [adaptor/proxy]         destination:/var/run/secrets/kubernetes.io/serviceaccount source:/run/kata-containers/shared/containers/a85cbf02527556217f118860cea0d64e69676fea5ff7c1f7c8d1ae12711c386b-558492c2fe2049ef-serviceaccount type:bind
2023/10/12 00:17:09 [adaptor/proxy]     annotations:
2023/10/12 00:17:09 [adaptor/proxy]         io.kubernetes.cri.sandbox-id: a42f354c7c73f95edd9dcedefb5f9ed5d7ef53678ef9ce821150d072957fd1f9
2023/10/12 00:17:09 [adaptor/proxy]         io.kubernetes.cri.image-name: docker.io/library/nginx:latest
2023/10/12 00:17:09 [adaptor/proxy]         io.kubernetes.cri.container-type: container
2023/10/12 00:17:09 [adaptor/proxy]         io.kubernetes.cri.container-name: nginx
2023/10/12 00:17:09 [adaptor/proxy]         io.katacontainers.pkg.oci.container_type: pod_container
2023/10/12 00:17:09 [adaptor/proxy]         io.katacontainers.pkg.oci.bundle_path: /run/containerd/io.containerd.runtime.v2.task/k8s.io/a85cbf02527556217f118860cea0d64e69676fea5ff7c1f7c8d1ae12711c386b
2023/10/12 00:17:09 [adaptor/proxy]         io.kubernetes.cri.sandbox-namespace: default
2023/10/12 00:17:09 [adaptor/proxy]         io.kubernetes.cri.sandbox-name: nginx
2023/10/12 00:17:09 [adaptor/proxy] getImageName: got image from annotations: docker.io/library/nginx:latest
2023/10/12 00:17:09 [adaptor/proxy] CreateContainer: calling PullImage for "docker.io/library/nginx:latest" before CreateContainer (cid: "a85cbf02527556217f118860cea0d64e69676fea5ff7c1f7c8d1ae12711c386b")
2023/10/12 00:17:13 [adaptor/proxy] CreateContainer: successfully pulled image "docker.io/library/nginx:latest"
2023/10/12 00:17:14 [adaptor/proxy] StartContainer: containerID:a85cbf02527556217f118860cea0d64e69676fea5ff7c1f7c8d1ae12711c386b
```

**Comment by huoqifeng** [comment]
From the logs, there is a `driver:image_guest_pull` appended both for pause and nginx container in the CreateContainer request.
```
2023/10/11 14:36:00 [adaptor/proxy]     storages:
2023/10/11 14:36:00 [adaptor/proxy]         mount_point:/run/kata-containers/23f3c16bd7118748a85f8d2405de1ba108825e56a0ac9433fb8ed5a1e2b109ad/rootfs source:pause fstype:overlay driver:image_guest_pull


2023/10/11 14:36:02 [adaptor/proxy]     storages:
2023/10/11 14:36:02 [adaptor/proxy]         mount_point:/run/kata-containers/e71f66fb91ce34ff31d1e2ab33a53f40b54527feff83a81b68bcfd7242310ce0/rootfs source:docker.io/library/nginx:latest fstype:overlay driver:image_guest_pull

```

**Comment by huoqifeng** [comment]
When test the scenario, I noticed the probe added in https://github.com/confidential-containers/cloud-api-adaptor/blob/main/cmd/cloud-api-adaptor/main.go#L154 should have a condition so that we can still start CAA as a service. I'll address it in a separate PR.

**Comment by huoqifeng** [comment]
Reported https://pkg.go.dev/vuln/GO-2023-2102 in the vulscan.

**Review by yoheiueda — APPROVED** [review]
LGTM. Thank you very much!

I think we will be able to remove the workaround code in the `else` clause, when everything becomes ready

**Review by liudalibj — APPROVED** [review]
LGTM

**Comment by huoqifeng** [comment]
> LGTM. Thank you very much!
> 
> I think we will be able to remove the workaround code in the `else` clause, when everything becomes ready

Currently CRI-O does not support remote-snapshotter, so we might keep some times before CRI-O has a solution.

**Pull request merged**
