### PR TITLE
podnetwork: Fix networking when using OVS

### PR DESCRIPTION
**Pull request by bpradipt**
When using OVS (OpenvSwitch) based CNIs like openshift-sdn or ovn-kubernetes, POD IPs are unreachable from the cluster nodes (worker or controller).
There are two issues at play here
- OVS based CNIs uses flow rules specific to the mac address of pod. And the pod mac address is used from the CNI created namespace on the worker node. However the container process which runs in the Pod VM uses a different mac address and unless the flow rules are updated with the mac address from the Pod VM, Pod IP is not reachable from the cluster nodes
- Certain CNIs (eg ovn-kubernetes) disables ARP broadcast and uses the pod mac address assigned by the CNI. However it doesn't matches with the mac address used in Pod VM and hence packets are received by the Pod VM with incorrect dst address over the vxlan tunnel

To fix the issues, this PR uses the CNI assigned MAC address for the POD VM vxlan0 interface.

Fixes: #369
Signed-off-by: Pradipta Banerjee <pradipta.banerjee@gmail.com>

### CODE REVIEW

**Comment by bpradipt** [comment]
Tested with calico, sdn and ovn-kubernetes

**Review by huoqifeng — APPROVED** [review]
/lgtm
thanks @bpradipt figure out and fixed the problem! I suggest add the diagram here https://github.com/confidential-containers/cloud-api-adaptor/issues/369#issue-1464062792 into a document to help illustrate the CNI network when using OVS or ovn-kubernetes

**Comment by bpradipt** [comment]
> /lgtm thanks @bpradipt figure out and fixed the problem! I suggest add the diagram here [#369 (comment)](https://github.com/confidential-containers/cloud-api-adaptor/issues/369#issue-1464062792) into a document to help illustrate the CNI network when using OVS or ovn-kubernetes

@huoqifeng yeah, I'll raise a PR to add network topology diagram for flannel, sdn and ovn.

**Review by snir911 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
