### PR TITLE
workflow: Add actionlint workflows

### PR DESCRIPTION
**Pull request by stevenhorsman**
On PRs that update anything in the workflows directory, add an actionlint run to validate our workflow files for errors and hopefully catch issues earlier.

Also fix the many issues we already have!

### CODE REVIEW

**Comment by stevenhorsman** [comment]
The run against my fork can be seen: https://github.com/stevenhorsman/cloud-api-adaptor/actions/runs/11744726638/job/32720502155, but I was hoping that the workflow would be run on this PR as well, so I'm not sure if I've made a mistake with it?

**Review by mkulke — APPROVED** [review]

**Comment by wainersm** [comment]
Hi @stevenhorsman !

> The run against my fork can be seen: https://github.com/stevenhorsman/cloud-api-adaptor/actions/runs/11744726638/job/32720502155, but I was hoping that the workflow would be run on this PR as well, so I'm not sure if I've made a mistake with it?

There is a typo on the `paths` filter: s/worksflows/workflows/
So it's expecting changes on wrong path. In your fork you probably triggered manually (workflow_dispatch).

**Comment by stevenhorsman** [comment]
> Hi @stevenhorsman !
> 
> > The run against my fork can be seen: https://github.com/stevenhorsman/cloud-api-adaptor/actions/runs/11744726638/job/32720502155, but I was hoping that the workflow would be run on this PR as well, so I'm not sure if I've made a mistake with it?
> 
> There is a typo on the `paths` filter: s/worksflows/workflows/ So it's expecting changes on wrong path. In your fork you probably triggered manually (workflow_dispatch).

Awesome - thanks for the spot I knew there was something wrong - and I did do the workflow_dispatch in my fork!

**Comment by stevenhorsman** [comment]
It's running now: https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/11819549958/job/32929721287?pr=2146. Big thank you to @wainersm!

**Review by wainersm — APPROVED** [review]
LGTM. Thanks @stevenhorsman !

**Pull request merged**
