### PR TITLE
aws,libvirt,azure,vsphere: allow authentication against container image registries

### PR DESCRIPTION
**Pull request by snir911**
from within the podvm

Fixes: #367

tested only with AWS

### CODE REVIEW

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @snir911

**Review by stevenhorsman — APPROVED** [review]
I can't test this as is not applicable to ibm cloud provider, but it makes sense and follows the temporary instructions to get authenticated registry support working in the short term. It's worth noting that when we get authenticated registry with image-rs working upstream we'll need to change this, so don't let me forget about that! Thanks @snir911

**Review by whitebrandy — COMMENTED** [review]
While going through what has changed recently, I noticed these binary additions. Is there a reason for adding agent-protocol-forwarder and kata-agent ?

**Comment by stevenhorsman** [comment]
@whitebrandy - Hey I'm a bit confused by your question, which binary addition to where is confusing you?

**Comment by whitebrandy** [comment]
@stevenhorsman sorry, i couldn't find a way to post that comment in context. If you look at what files have been changed:
BIN +16.9 MB
[libvirt/image/files/usr/local/bin/agent-protocol-forwarder]
Binary file not shown.
BIN +28.9 MB
[libvirt/image/files/usr/local/bin/kata-agent]
Binary file not shown.

**Comment by stevenhorsman** [comment]
> @stevenhorsman sorry, i couldn't find a way to post that comment in context. If you look at what files have been changed: BIN +16.9 MB [libvirt/image/files/usr/local/bin/agent-protocol-forwarder] Binary file not shown. BIN +28.9 MB [libvirt/image/files/usr/local/bin/kata-agent] Binary file not shown.

Oh, sorry I completely missed that in my review. I guess something that snuck in accidentally? @snir911 - is this correct and if so can you raise a PR to reverse those?

@whitebrandy - thanks so much for noticing and keeping us honest!

**Pull request merged**
