### PR TITLE
Revert "Build: Update build.sh"

### PR DESCRIPTION
**Pull request by stevenhorsman**
This reverts commit f1fd4d9da8d1a6353d208ed6ed5f44649ff5a8b1.

Fixes: #1792

### CODE REVIEW

**Review by beraldoleal — APPROVED** [review]
LGTM

**Comment by portersrc** [comment]
lgtm

**Review by wainersm — APPROVED** [review]
LGTM. It seems that we still need to push to `${registry}/${name}`

**Comment by stevenhorsman** [comment]
> LGTM. It seems that we still need to push to `${registry}/${name}`

I think it might be part of the `tag_string` (with the `-t ` removed) rather than `${registry}/${name}` as that wasn't created by the buildx step before

**Pull request merged**
