### PR TITLE
pkg: clean socket if exist

### PR DESCRIPTION
**Pull request by snir911**
if exist bind may fail

Fixes: #65
Signed-off-by: Snir Sheriber <ssheribe@redhat.com>

### CODE REVIEW

**Review by bpradipt — APPROVED** [review]
@snir911 the patch looks good to me
Need to check why the CI is failing.

**Comment by bpradipt** [comment]
@snir911 can you please rebase and push.

**Comment by snir911** [comment]
Rebased, I don't have powers on the repo though, may i get some ;) ?

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @snir911

**Pull request merged**
