### PR TITLE
Docker: podvm image: remove systemd tmpfiles setup delete

### PR DESCRIPTION
**Pull request by stevenhorsman**
Remove the systemd "systemd-tmpfiles-setup.service" -delete
and tidy up docs and code to remove missing features

### CODE REVIEW

**Review by mkulke — COMMENTED** [review]
I feel like we should untangle both aspects. One is a bug with the docker provider, the other issue is a regression that we should be able to fix in mkosi one way or the other, possibly with variables in the mkosi or docker builds

**Comment by stevenhorsman** [comment]
> I feel like we should untangle both aspects. One is a bug with the docker provider, the other issue is a regression that we should be able to fix in mkosi one way or the other, possibly with variables in the mkosi or docker builds

So are you proposing that I drop the second commit and ignore it completely, or move it to a different PR?

**Comment by mkulke** [comment]
> > I feel like we should untangle both aspects. One is a bug with the docker provider, the other issue is a regression that we should be able to fix in mkosi one way or the other, possibly with variables in the mkosi or docker builds
> 
> So are you proposing that I drop the second commit and ignore it completely, or move it to a different PR?

I'd suggest to open an issue regarding the second issue. I suspect we want to keep the ability of specifying policies at build-time

**Review by mkulke — APPROVED** [review]

**Comment by stevenhorsman** [comment]
> I'd suggest to open an issue regarding the second issue. I suspect we want to keep the ability of specifying policies at build-time

Done: https://github.com/confidential-containers/cloud-api-adaptor/issues/2045

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by bpradipt** [comment]
@stevenhorsman do we need the e2e libvirt test for this PR ?

**Comment by stevenhorsman** [comment]
> @stevenhorsman do we need the e2e libvirt test for this PR ?

Good point - this only impacts the docker provider, so I think we can ignore that

**Comment by bpradipt** [comment]
Merging this as e2 libvirt is not relevant for this PR.

**Pull request merged**
