### PR TITLE
golang: upgrade to 1.22.7

### PR DESCRIPTION
**Pull request by bpradipt**
Fixes Vulnerability #1: GO-2024-3106

### CODE REVIEW

**Review by mkulke — APPROVED** [review]

**Review by stevenhorsman — COMMENTED** [review]
I think you missed:
- https://github.com/bpradipt/cloud-api-adaptor/blob/3293613ca799154180f1595e5e788b8be173e7fd/src/cloud-api-adaptor/podvm/README.md?plain=1#L60 (though when my podvm version removal PR merges that will be deleted)

Were you planning to follow up with a separate PR to bump:
- https://github.com/bpradipt/cloud-api-adaptor/blob/3293613ca799154180f1595e5e788b8be173e7fd/src/cloud-api-adaptor/docs/addnewprovider.md?plain=1#L211
- https://github.com/bpradipt/cloud-api-adaptor/blob/3293613ca799154180f1595e5e788b8be173e7fd/src/peerpod-ctrl/Dockerfile#L2
If so I think it makes sense to move the change to https://github.com/bpradipt/cloud-api-adaptor/blob/3293613ca799154180f1595e5e788b8be173e7fd/src/cloud-api-adaptor/Dockerfile#L2 in that PR as well?

**Comment by bpradipt** [comment]
> I think you missed:
> 
> * https://github.com/bpradipt/cloud-api-adaptor/blob/3293613ca799154180f1595e5e788b8be173e7fd/src/cloud-api-adaptor/podvm/README.md?plain=1#L60 (though when my podvm version removal PR merges that will be deleted)
> 
> Were you planning to follow up with a separate PR to bump:
> 
> * https://github.com/bpradipt/cloud-api-adaptor/blob/3293613ca799154180f1595e5e788b8be173e7fd/src/cloud-api-adaptor/docs/addnewprovider.md?plain=1#L211
> * https://github.com/bpradipt/cloud-api-adaptor/blob/3293613ca799154180f1595e5e788b8be173e7fd/src/peerpod-ctrl/Dockerfile#L2
>   If so I think it makes sense to move the change to https://github.com/bpradipt/cloud-api-adaptor/blob/3293613ca799154180f1595e5e788b8be173e7fd/src/cloud-api-adaptor/Dockerfile#L2 in that PR as well?

I missed the READMEs. Thanks for the pointers. Will update it.

**Comment by bpradipt** [comment]
@stevenhorsman should I move the changes dependent on the golang fedora image version into a separate PR?

**Comment by stevenhorsman** [comment]
> @stevenhorsman should I move the changes dependent on the golang fedora image version into a separate PR?

We've had two different approaches for this:
1. Have two PRs; wait for the golang fedora image to get merged in one and built then have the second one that uses it. This has the advantage of everything staying green
2. Just do it all in one and manually re-run the builds that fail. This has the advantage of needing one less review cycle and as reviewers are hard to find recently, we've been doing this approach

I think given this is a major golang bump maybe approach 1 is safer this time?

**Comment by bpradipt** [comment]
Created a separate PR to update the fedora golang image - https://github.com/confidential-containers/cloud-api-adaptor/pull/2031
Once 2031 is merged, will update this PR

**Comment by stevenhorsman** [comment]
https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/10771064012 shows that the image has been built now.

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Comment by bpradipt** [comment]
The e2 tests are timing out. I do see pod creation tests successfully executed. Maybe the timeout for the e2e tests could be increased.
@stevenhorsman @mkulke should I merge this PR?

**Comment by bpradipt** [comment]
> TestLibvirtCreateNginxDeployment is flakey and when it fails we are likely to trigger the timeout, but I'll try and get some more concrete info on this. Maybe that test is a candidate to only run on nightly and not PRs?

I'll also take a look at this test. Let's discuss this in our next community interlock. Probably by that time we'll have more insights on the flakiness.

**Pull request merged**
