### PR TITLE
deps: upgrade to Go 1.20.5

### PR DESCRIPTION
**Pull request by katexochen**
Upgrading to the latest Go version.

Fixes: #1139

### CODE REVIEW

**Comment by katexochen** [comment]
The CI failure of controller test seems to be on GitHub's side, could anyone trigger a re-run? @bpradipt @stevenhorsman 

Btw, is there a team like @confidential-containers/cloud-api-adaptor-maintainers one can mention?

**Comment by stevenhorsman** [comment]
> Btw, is there a team like @confidential-containers/cloud-api-adaptor-maintainers one can mention?

Yes - the team is peer-pod-maintainers. I've also invited you to peer-pod-commiters, so you should be able to re-run the GHA yourself now

**Comment by katexochen** [comment]
Thank you so much @stevenhorsman, happy to be part of the team! :blush:

**Comment by stevenhorsman** [comment]
> Thank you so much @stevenhorsman, happy to be part of the team! 😊

You deserve for your contribution and the difference you've made, so thank you!

**Comment by stevenhorsman** [comment]
On this actual PR - we were trying to stay in sync with the kata-container's version of go (which is back on 1.19.3) for stability reasons, but if 1.20.5 is working and we keep the `go.mod` versions at 1.19 for compatibility, then I don't think there should be any issues?

**Comment by katexochen** [comment]
> and we keep the go.mod versions at 1.19 for compatibility

That would only be relevant if kata-containers would import cloud-api-adaptor as Go module, which it doesn't, right? If no other module with smaller module version imports cloud-api-adaptor, we can use the newest set of features regardless of what out dependencies do.

Go has strong backward-compatibility promises. Building code that uses an older feature set (like kata, with a smaller version in go.mod) can (and should) always be built with the newest Go toolchain/command. Using the newest toolchain will ensure that the latest security fixes in the standard library will be included in the binary (I also tried to explain this in https://github.com/confidential-containers/cloud-api-adaptor/pull/1116#discussion_r1242598594).

You can check locally, if you have an older Go command installed, run:

```shell
go install golang.org/x/vuln/cmd/govulncheck@latest
govulncheck ./...
```

**Comment by stevenhorsman** [comment]
Thanks for the extra explanation!

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Comment by bpradipt** [comment]
> > Btw, is there a team like @confidential-containers/cloud-api-adaptor-maintainers one can mention?
> 
> Yes - the team is peer-pod-maintainers. I've also invited you to peer-pod-commiters, so you should be able to re-run the GHA yourself now

This was due. Thanks @stevenhorsman for doing the needful.
@katexochen thanks a lot for your contributions

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @katexochen

**Pull request merged**
