### PR TITLE
versions: Bump golang

### PR DESCRIPTION
**Pull request by stevenhorsman**
Bump to go 1.21.8 to resolve CVEs:
- https://pkg.go.dev/vuln/GO-2024-2600
- https://pkg.go.dev/vuln/GO-2024-2599
- https://pkg.go.dev/vuln/GO-2024-2598
- https://pkg.go.dev/vuln/GO-2024-2610
- https://pkg.go.dev/vuln/GO-2024-2611

### CODE REVIEW

**Review by mkulke — APPROVED** [review]

**Comment by liudalibj** [comment]
@stevenhorsman to fix the error from govulncheck for csi-wrapper please try follow
```
volumes/csi-wrapper
go get github.com/golang/protobuf@v1.5.4
go mod tidy
```
the output looks like:
```
go: downloading github.com/golang/protobuf v1.5.4
go: downloading google.golang.org/protobuf v1.33.0
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
go: upgraded github.com/golang/protobuf v1.5.3 => v1.5.4
go: upgraded google.golang.org/protobuf v1.30.0 => v1.33.0
```

**Comment by stevenhorsman** [comment]
The golvuln is fixed now, but we are hitting typecheck errors in the linting check now, I guess due to differences in the package we've upgraded, so I'll dig into those more when I get a chance later.

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by stevenhorsman** [comment]
@liudalibj - I wonder if you can help with the issues I'm seeing on this PR now. After doing your suggested changes the govuln is clean, but I get thousands of lint errors now as some of them are in the generated csi-wrapper code I tried re-running `go mod vendor` and `./examples/update-codegen.sh` but they don't seem to make any difference. Do you have any ideas?

**Comment by liudalibj** [comment]
> @liudalibj - I wonder if you can help with the issues I'm seeing on this PR now. After doing your suggested changes the govuln is clean, but I get thousands of lint errors now as some of them are in the generated csi-wrapper code I tried re-running `go mod vendor` and `./examples/update-codegen.sh` but they don't seem to make any difference. Do you have any ideas?

I will take a look on this issue today.

**Review by liudalibj — APPROVED** [review]
LGTM.

**Comment by liudalibj** [comment]
> > @liudalibj - I wonder if you can help with the issues I'm seeing on this PR now. After doing your suggested changes the govuln is clean, but I get thousands of lint errors now as some of them are in the generated csi-wrapper code I tried re-running `go mod vendor` and `./examples/update-codegen.sh` but they don't seem to make any difference. Do you have any ideas?
> 
> I will take a look on this issue today.

@stevenhorsman the lint issue is fixed by using the latest golint version `1.56.2`, please double check and continue.

**Comment by stevenhorsman** [comment]
> @stevenhorsman the lint issue is fixed by using the latest golint version 1.56.2, please double check and continue.

Thanks so much - I was obviously following red herrings looking at the generated code!

**Pull request merged**
