### PR TITLE
Resolve kustomize warnings

### PR DESCRIPTION
**Pull request by ldoktor**
While setting-up my libvirt+kcli I noticed a few warnings from kustomize. I used `kustomize edit fix` to learn what to replace and then addressed all places using `sed`. Note the behaviour should not change but I have only tested the default libvirt e2e setup with kcli.

### CODE REVIEW

**Comment by wainersm** [comment]
Hi @ldoktor !

This PR is very welcome; I changed some of those deprecation while ago in a project that I don't recall anymore :(

However, due to the recent changes on the layout of the repository (https://github.com/confidential-containers/cloud-api-adaptor/pull/1719) you will need to rebase/recreate the PR :(

**Review by wainersm — APPROVED** [review]
Thanks @ldoktor !

**Comment by stevenhorsman** [comment]
We had some issues in the past that some of our test code wasn't compatible with the new kustomize format, so a couple of us made this change before and had to back it out (e.g. https://github.com/confidential-containers/cloud-api-adaptor/issues/1023), but maybe we have bumped versions enough for it to work now?

**Comment by stevenhorsman** [comment]
It looks to work on IBM Cloud so far, but I'm still hitting kustomize warnings:
```
$ kubectl apply -k install/overlays/ibmcloud
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically
```
May switching those were the blocking issues we had before?

**Review by stevenhorsman — APPROVED** [review]
I think there are some other warnings still kicking around, but it's still an improvement to remove these. Thanks @ldoktor!

**Pull request merged**
