### PR TITLE
podvm: remove CentOS support

### LINKED ISSUE #1558: centos ssh timeout on podvm image build
During release build testing I've noticed that the centos image build is not able to complete.

Extract from the packer logs which might be relevant 

```
rcu: INFO: rcu_preempt detected stalls on CPUs/tasks:
rcu: 	0-...!: (0 ticks this GP) idle=4268/0/0x0 softirq=173/173 fqs=0 (false positive?)
	(detected by 1, t=60005 jiffies, g=-1119, q=6021 ncpus=2)
Sending NMI from CPU 1 to CPUs 0:
NMI backtrace for cpu 0 skipped: idling at default_idle+0xb/0x10
rcu: rcu_preempt kthread timer wakeup didn't happen for 60002 jiffies! g-1119 f0x0 RCU_GP_WAIT_FQS(5) ->state=0x402
rcu: 	Possible timer handling issue on cpu=0 timer-softirq=15
rcu: rcu_preempt kthread starved for 60005 jiffies! g-1119 f0x0 RCU_GP_WAIT_FQS(5) ->state=0x402 ->cpu=0
rcu: 	Unless rcu_preempt kthread gets sufficient CPU time, OOM is now expected behavior.
rcu: RCU grace-period kthread stack dump:
task:rcu_preempt     state:I stack:0     pid:17    ppid:2      flags:0x00004000
Call Trace:
 <TASK>
 __schedule+0x20a/0x550
 ? __pfx_rcu_gp_kthread+0x10/0x10
 schedule+0x2d/0x70
 schedule_timeout+0x88/0x160
 ? __pfx_process_timeout+0x10/0x10
 rcu_gp_fqs_loop+0x114/0x460
 rcu_gp_kthread+0xfb/0x190
 kthread+0xe0/0x100
 ? __pfx_kthread+0x10/0x10
 ret_from_fork+0x2c/0x50
 </TASK>
rcu: Stack dump where RCU GP kthread last ran:
Sending NMI from CPU 1 to CPUs 0:
NMI backtrace for cpu 0 skipped: idling at default_idle+0xb/0x10
```

### PR DESCRIPTION
**Pull request by wainersm**
The podvm build for CentOS has been broken for a while now (see #1558) and even on the last release (0.8.0) we didn't publish an image. After some discussions in https://github.com/confidential-containers/cloud-api-adaptor/pull/1564 and in our community's meeting today there is a consensus that CentOS support can be dropped.

Important to say that we will continue building an RPM-based distro (Fedora) but with the mkosi tool instead of packer.

Somehow-fixes #1558
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks

**Comment by wainersm** [comment]
Tested this PR in https://github.com/wainersm/cc-cloud-api-adaptor/actions/runs/7120480521 . It was able to build the builder, binaries and podvm images only of Ubuntu.

**Review by liudalibj — APPROVED** [review]
LGTM

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @wainersm

**Pull request merged**
