### PR TITLE
Kata agent config cleanup

### PR DESCRIPTION
**Pull request by stevenhorsman**

### CODE REVIEW

**Comment by stevenhorsman** [comment]
Just an update on this - there is something wrong with the server address not flowing through:
```
server_addr: \"vsock://-1:1024\"
```
which explains the comment that was added in the agent-config.toml. I will try and debug it to see if I can work out the cause...

**Comment by stevenhorsman** [comment]
Ok, I think there is a bug in the kata config processing, so I'll try and fix that up and then re-test this.

**Comment by stevenhorsman** [comment]
FYI: https://github.com/kata-containers/kata-containers/pull/9819 is my attempt to fix and let envs being processed with the config file

**Review by mkulke — APPROVED** [review]

**Review by huoqifeng — APPROVED** [review]
LGTM
Glad to see `endpoints` get removed, thanks! @stevenhorsman

**Review by bpradipt — APPROVED** [review]
/lgtm

**Pull request merged**
