### PR TITLE
e2e-ibmcloud: quick fix to unblock ibmcloud e2e test

### PR DESCRIPTION
**Pull request by liudalibj**
- use old style of install/overlays/ibmcloud/kustomization.yaml

fixes: #1021

### CODE REVIEW

**Review by huoqifeng — APPROVED** [review]
/lgtm
@liudalibj I agree we have a quick fix before update kustomize version to the newest v5.0.4 from v2.0.3+incompatible

**Review by yoheiueda — APPROVED** [review]
LGTM

**Review by stevenhorsman — APPROVED** [review]
Thanks for the fix DaLi, lets get this merged now and then have an issues to update `v2.0.3+incompatible` and the kustomization.yaml fix ASAP in the next cycle.

**Comment by liudalibj** [comment]
> update `v2.0.3+incompatible` and the kustomization.yaml fix ASAP in the next cycle.

Created a new issue https://github.com/confidential-containers/cloud-api-adaptor/issues/1023

**Pull request merged**
