### PR TITLE
powervs: use public IP to connect to the peer pod vm

### PR DESCRIPTION
**Pull request by Amulyam24**
Adds support to use public IP to connect to the agent-protocol-forwarder running in the peer pod VM.

Fixes: #1461

### CODE REVIEW

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @Amulyam24

**Review by jtumber-ibm — APPROVED** [review]

**Comment by surajssd** [comment]
I am wondering if this is safe to communicate over the internet to the peer pod vm?

**Comment by bpradipt** [comment]
> I am wondering if this is safe to communicate over the internet to the peer pod vm?

It comes with risks. The communication between the CAA and agent-protocol-forwarder is over TLS, but any pod-to-pod network communication will be over the (unencrypted) vxlan which is a risk. Pod VM networking can be configured to ensure any external traffic is not routed via the worker node. 

There were some initial work done to encrypt the traffic between worker node and podvm - https://github.com/confidential-containers/cloud-api-adaptor/issues/688

**Comment by surajssd** [comment]
Alright, just wanted to see that we are doing this change for the IBM provider knowingly. Good to know that @bpradipt, thanks.

**Pull request merged**
