### PR TITLE
all: migrate from k8s.gcr.io to registry.k8s.io

### PR DESCRIPTION
**Pull request by CIPHERTron**
This fix is a part of an umbrella issue https://github.com/kubernetes/k8s.io/issues/4780

### CODE REVIEW

**Review by snir911 — APPROVED** [review]
Thanks for the patch, LGTM overall
nit, if you don't mind please add `Fixes: kubernetes/k8s.io#4780` to the commit msg for reference (also very nit-i think `all:` would fit better than `fix:`)

**Comment by CIPHERTron** [comment]
> Thanks for the patch, LGTM overall nit, if you don't mind please add `Fixes: kubernetes/k8s.io#4780` to the commit msg for reference (also very nit-i think `all:` would fit better than `fix:`)

@snir911 I've addressed your comments. PTAL. Thanks!

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @CIPHERTron

**Comment by bpradipt** [comment]
Force merging this.

**Pull request merged**
